== Beskrivelse av datatjeneste [[beskrivelse-av-datatjeneste]]

Nytt i DCAT-AP-NO v.2 er at standarden nå også støtter beskrivelser av datatjenester, som v.1.x av DCAT-AP-NO ikke gjorde.

Datatjeneste (dcat:DataService) brukes til å beskrive en samling av operasjoner som er tilgjengelig via et programmeringsgrensesnitt (API) og som gir tilgang til ett eller flere datasett eller databehandlingsfunksjoner.

=== Eksempel på en datatjenestebeskrivelse [[eksempel-datatjeneste]]

Under er et eksempel på en datatjenestebeskrivelse, hvor felter med uthevet skrift er obligatoriske:

*****
*Eksempel på en datatjenestebeskrivelse*: +

https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-endepunktsurl[*EndepunktsURL*]: +https://example.org/endpoints+ +
https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-identifikator[*Identifikator*]: +https://example.org/dataservices/9564be66-5543-36b6-9a4d-150b94e4e03b+ +
https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-tittel[*Tittel*]: REST-API for eksempler +
https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-endepunktsbeskrivelse[Endepunktsbeskrivelse]: Lenke til beskrivelse eller tekst inn her??? +
https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-format[Format]: JSON +
https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-utgiver[Utgiver]: Digitaliseringsdirektoratet
*****

_Eksempel i RDF Turtle_ [yellow-background]#<kommer...>#

=== Obligatoriske egenskaper i en datatjenestebeskrivelse [[datatjeneste-obligatoriske-egenskaper]]
Som et minimum skal følgende tas med i en datatjenestebeskrivelse:

* Datatjeneste - endepunktsURL: rotplassering eller primært endepunkt for tjenesten.
* Datatjeneste - identifikator: identifikator til datatjenesten.
* Datatjeneste - tittel: navn på datatjenesten.

==== Datatjeneste - endepunktsURL [[datatjeneste-endepunktsURL]]
Refererer til rotplassering eller primært endepunkt for tjenesten (en URI) [https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-endepunktsurl[Datatjeneste: endepunktsURL]].

_Eksempel i RDF Turtle_

----
<> a dcat:DataService ;
  dcat:endpointURL <https://example.org/endpoints> .
----
==== Datatjeneste - identifikator [[datatjeneste-identifikator]]
Brukes til å oppgi identifikator til datatjenesten.

Se under <<om-identifikator, Om identifikator>>.

==== Datatjeneste - tittel [[datatjeneste-tittel]]
Feltet brukes til å oppgi navnet på datatjenesten. Gjentas hvis navnet er i flere språk.

_Eksempel i RDF Turtle_
----
<> a dcat:DataService ;
  dct:title "FDK API endpoints"@en ,
    "FDK API endepunkter"@nb .
----
=== Anbefalte egenskaper i en datatjenestebeskrivelse [[datatjeneste-anbefalte-egenskaper]]
Følgende opplysninger bør du ta med i en datatjenestebeskrivelse hvis de finnes:

* Datatjeneste - emneord: emneord (eller tag) som beskriver datatjenesten.
* Datatjeneste - endepunktsbeskrivelse: beskrivelse av tjenesten.
* Datatjeneste - format: datatjenestens filformat.
* Datatjeneste - kontaktpunkt: kontaktpunkt med kontaktopplysninger.
* Datatjeneste - tema: tema for datatjenesten.
* Datatjeneste - tilgjengeliggjør datasett: datasett som datatjenesten kan distribuere.
* Datatjeneste - utgiver: aktør (organisasjon) som er ansvarlig for å gjøre datatjenesten tilgjengelig.

==== Datatjeneste - emneord [[datatjeneste-emneord]]
Inneholder emneord (eller tag) som beskriver datatjenesten https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-emneord[Datatjeneste: emneord].
Se beskrivelsen av tilsvarende felt i Datasett, https://data.norge.no/specification/dcat-ap-no/#Datasett-emneord[Datatjeneste: emneord].


==== Datatjeneste - endepunktsbeskrivelse [[datatjeneste-endepunktsbeskrivelse]]

Beskrivelse av tjenesten [https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-endepunktsbeskrivelse[Datatjeneste: endepunktsbeskrivelse]].

Brukes primært til å lenke til en formalisert beskrivelse av tjenestene som er tilgjengelige via endepunktene, inkludert deres operasjoner, parametere osv. Beskrivelsen skal gi spesifikke detaljer om de faktiske endepunkt-instansene, mens `dct:conformsTo` brukes til å indikere den generelle standarden eller spesifikasjonen som endepunktene implementerer.

* Lenke til en maskinlesbar formalisert endepunktbeskrivelse, som for eksempel en Open API (Swagger) beskrivelse [https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.w3.org%2FTR%2Fvocab-dcat-2%2F%23bib-openapi&data=04%7C01%7C%7Cefe2137342004d9c6ffb08d93a04785b%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637604613147600182%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EwlvzY76t%2FcuW%2Ff0y8FYiImKU2eMo75ZxvYyBM2SYXg%3D&reserved=0[OpenAPI]], GraphQL [https://graphql.org/[GraphQL]].
* Dersom en formalisert beskrivelse ikke er mulig, kan det lenkes til en tekstlig beskrivelse


_Eksempel i RDF Turtle_ +
----
<> a dcat:DataService ;
  dcat:endpointDescription <https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-api-endpoints/master/specification/fdk-api-endpoints.yaml> . # peker til en OpenAPI spesifikasjon av tjenesten
----

==== Datatjeneste - format [[datatjeneste-format]]
Datatjenestens filformat.

* EUs kontrollerte liste over https://op.europa.eu/s/pcDP[File type] skal brukes.
* Kan gjentas for API-er og sluttbrukerapplikasjoner som leverer data i flere formater.
_Eksempel i RDF Turtle_ +
----
<> a dcat:DataService ;
  dct:format <http://publications.europa.eu/resource/authority/file-type/JSON_LD> , # JSON-LD
    <http://publications.europa.eu/resource/authority/file-type/RDF_TURTLE> . # RDF Turtle
----
==== Datatjeneste - kontaktpunkt [[datatjeneste-kontaktpunkt]]
Kontaktpunkt med kontaktopplysninger https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-kontaktpunkt[Datatjeneste: kontaktpunkt]. Se ellers beskrivelsen av tilsvarende felt i Datasett, https://data.norge.no/specification/dcat-ap-no/#Datasett-kontaktpunkt[Datasett - kontaktpunkt]. +

==== Datatjeneste - tema [[datatjeneste-tema]]
Tema for datatjenesten. En datatjeneste kan assosieres med flere tema. +
For å kunne sortere datatjenesten inn under gitte kategorier er det behov for tema.

* Ett eller flere temaer skal velges fra https://op.europa.eu/s/oZjL[den kontrollerte listen av EU-temaer].

* Ett eller flere temaer bør velges fra https://psi.norge.no/los/struktur.html[det norske LOS-vokabularet]. Merk at Los har flere nivåer og at de overordnede nivåene er implisitt når en velger tema på nivå 2 og 3 i hierarkiet.

_Eksempler_

*  *Helse* (+HEAL+ fra EU-listen)
*  *Helsestasjon* (+helsestasjon+ fra LOS)

_Eksempel i RDF Turtle_

----
<> a dcat:DataService ;
  dcat:theme <http://publications.europa.eu/resource/authority/data-theme/HEAL> , # helse
    <https://psi.norge.no/los/ord/helsestasjon> . # helsestasjon (Helse og omsorg -> Helsetjenester -> Helsestasjon)
----
==== Datatjeneste - tilgjengeliggjør datasett [[datatjeneste-tilgjengeliggjørDatasett]]
Feltet brukes til å referere til datasett som datatjenesten kan distribuere.

_Eksempel i RDF Turtle_

----
<> a dcat:DataService ;
  dcat:servesDataset <https://example.org/dataset/123> ,
    <https://example.org/dataset/456> . # peker til 2 datasett.
----
==== Datatjeneste - utgiver [[datatjeneste-utgiver]]

Identifisering av den aktøren (organisasjon) som er ansvarlig for å gjøre datatjenesten tilgjengelig.

* Skal peke på en virksomhet (juridisk person, organisasjonsledd, underenhet) som er ansvarlig utgiver - ikke leverandør av tjenesten.
* Det offisielle navnet på virksomheten vil bli hentet fra Enhetsregisteret, men kortform (f.eks. Digdir) kan legges inn av brukeren.
* Utgiveren av datasettet forvalter sammensetning av dataene, altså datasettet, og ikke nødvendigvis selve dataene.
Inntil https://data.brreg.no  tilbyr gyldig identifator (foaf:Agent), skal følgende mønster benyttes: `+https://organization-catalogue.fellesdatakatalog.digdir.no/organizations/{orgnummer}+`


_Eksempler_

*  Arbeids- og velferdsetaten

_Eksempel i RDF Turtle_
----
<> a dcat:DataService ;
  dct:publisher <https://organization-catalogue.fellesdatakatalog.digdir.no/organizations/889640782> . #NAV
----

=== Valgfrie egenskaper i en datatjenestebeskrivelse [[datatjeneste-valgfrie-egenskaper]]

I tillegg til obligatoriske (skal brukes) og anbefalte (bør brukes) felter, er det en del felter som er valgfrie (kan brukes) i en datatjenestebeskrivelse:

* Datatjeneste - beskrivelse: fritekstbeskrivelse av datatjenesten.
* Datatjeneste - dokumentasjon: side eller dokument som beskriver datatjenesten.
* Datatjeneste - følger: regel som definerer den juridiske rammen for datatjenesten.
* Datatjeneste - i samsvar med: spesifikasjon eller standard som datatjenesten implementerer.
* Datatjeneste - landingsside: nettside som gir tilgang til datatjenesten, dens distribusjoner og/eller tilleggsinformasjon.
* Datatjeneste - lisens: lisensen som datatjenesten blir gjort tilgjengelig under.
* Datatjeneste - tilgangsrettigheter: informasjon angående tilgang eller begrensninger basert på personvern, sikkerhet eller andre retningslinjer.
* Datatjeneste - type: datatjenestens type.

Ikke alle valgfrie felter er beskrevet i etterfølgende avsnitt. Se under <<hensikt-og-avgrensing, Hensikt og avgrensning>> for hvordan du kan melde inn behov for beskrivelser.

==== Datatjeneste - beskrivelse [[datatjeneste-beskrivelse]]

Fritekst-beskrivelse av datatjenesten. Gjentas for flere språkversjoner. Se ellers beskrivelsen av tilsvarende felt i Datasett, <<Datasett - beskrivelse>>.

* Kopier gjerne beskrivende informasjon fra dokumentasjonen eller landingssiden
* Ved behov for formatering av tekst - benytt https://Commonmark.org[CommonMark]



==== Datatjeneste - dokumentasjon [[datatjeneste-dokumentasjon]]

Referanse til en side eller et dokument som beskriver datatjenesten.

* Siden eller dokumentet som det linkes til bør være en menneskelesbar ressurs, i motsetning til endepunktbeskrivelse som primært er en maskinlesbar ressurs
* Se også beskrivelsen av <<datatjeneste-landingsside>>, <<datatjeneste-endepunktsbeskrivelse>> og <<datatjeneste-beskrivelse>>.

==== Datatjeneste - følger [[datatjeneste-følger]]

_<ikke beskrevet, tilsvarer [https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-f%C3%B8lger[Datatjeneste: følger]]>_

Se ellers beskrivelsen av tilsvarende felt i Datasett, <<datasett-følger, Datasett - følger>>.

==== Datatjeneste - i samsvar med [[datatjeneste-iSamsvarMed]]

Referanse til en spesifikasjon eller standard som datatjenesten implementerer.

* En datatjeneste kan være utviklet i samsvar med en eller flere standarder og/eller spesifikasjoner.
* Du kan knytte en informasjonsmodell (`modelldcatno:InformationModel`) til en datatjeneste ved hjelp av dette feltet.
* Vi anbefaler at informasjonsmodellen for endepunktet også inngår som en del av endepunktbeskrivelsen

==== Datatjeneste - landingsside [[datatjeneste-landingsside]]

_<ikke beskrevet, tilsvarer [https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-landingsside[Datatjeneste: landingsside]]>_

Se ellers beskrivelsen av tilsvarende felt i Datasett, <<datasett-landingsside, Datasett - landingsside>>.

==== Datatjeneste - lisens [[datatjeneste-lisens]]

Referanse til lisensen for datasett som datatjenesten realiserer, gjøres tilgjengelig under [https://data.norge.no/specification/dcat-ap-no/#Distribusjon-lisens[Distribusjon: lisens]]. Lisens er påkrevd for alle åpne offentlige data.

* EUs kontrollerte liste over https://op.europa.eu/s/o8vZ[Licence] skal brukes, dersom lisensen som benyttes finnes på listen.
* For åpne data skal en av disse tre lisensene benyttes:
** Creative Commons Navngivelse 4.0 (CC BY 4.0): `+http://publications.europa.eu/resource/authority/licence/CC_BY_4_0+`
** Creative Commons CC0 1.0 Universal (CC0): `+http://publications.europa.eu/resource/authority/licence/CC0+`
** Norsk lisens for offentlige data (NLOD): `+http://publications.europa.eu/resource/authority/licence/NLOD_2_0+`
* Creative Commons-lisensene anbefales for distribusjoner (og datatjenester) med forventet internasjonal bruk.

Se Digdirs  https://data.norge.no/guide/veileder-apne-data/[Veileder for tilgjengeliggjøring av åpne data] for mer informasjon om valg av åpne standardlisenser.

Se ellers beskrivelsen av tilsvarende felt i Distribusjon, <<distribusjon-lisens, Distribusjon - lisens>>.

==== Datatjeneste - tilgangsrettigheter [[datatjeneste-tilgangsrettigheter]]

_<ikke beskrevet, tilsvarer [https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-tilgangsrettigheter[Datatjeneste: tilgangsrettigheter]]>_

=== Datatjeneste - type [[datatjeneste-type]]

https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-type[Datatjeneste: type] er referanse til et begrep i en kontrollert liste som identifiserer datatjenestens type, for eksempel https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType
