== Beskrivelse av datasett [[beskrivelse-av-datasett]] 

Se https://data.norge.no/guide/veileder-orden-i-eget-hus/[Veileder for orden i eget hus] for hvordan din virksomhet kartlegger hvilke datasett som skal beskrives.

Hovedhensikten med å beskrive et datasett er at andre (internt eller eksternt) lettere skal kunne forstå hva slags datasett du har, for bl.a. å kunne vurdere om de kan gjenbruke/viderebruke dette datasettet fra deg.

For at andre skal kunne forstå dine beskrivelser, er det visse spilleregler for hvordan et datasett skal/bør/kan beskrives.

Dette kapittelet forklarer hvordan et datasett beskrives i henhold til kravene i forvaltningsstandarden https://data.norge.no/specification/dcat-ap-no/[DCAT-AP-NO v.2], dog uten at du må kunne DCAT-AP-NO.

For deg som skal utvikle/tilpasse verktøystøtte for datasettbeskrivelse i henhold til DCAT-AP-NO, inneholder veilederen også en teknisk veiledning bakerst i hvert avsnitt. NB! Bortsett fra det første eksemplet, er ikke alle eksempler i RDF Turtle komplette og de kan mangle bl.a. verdier for obligatoriske egenskaper.


=== Eksempel på en datasettbeskrivelse [[eksempel-datasettbeskrivelse]]

Under er et eksempel på en datasettbeskrivelse, med dummydata, hvor *uthevede egenskaper* er obligatoriske:

****
_Eksempel på en datasettbeskrivelse med dummydata, hvor *uthevede egenskaper* er obligatoriske:_

<<datasett-tittel, *Tittel*>>: Eksempeldatasett +
<<datasett-utgiver, *Utgiver*>>: Direktoratet for eksempler +
<<datasett-beskrivelse, *Beskrivelse*>>: Datasett med testdata.
Formålet med dette datasettet er å illustrere hvordan et datasett skal/bør/kan beskrives iht. DCAT-AP-NO. +
<<datasett-tema, *Tema*>>: https://op.europa.eu/s/pirn[Forvaltning og offentlig sektor] +
<<datasett-begrep, Begrep>>: https://op.europa.eu/s/piiD[testdata] +
<<datasett-dekningsområde, Dekningsområde>>: https://op.europa.eu/s/pirm[Norge] +
<<datasett-frekvens, Oppdateringsfrekvens>>: https://op.europa.eu/s/piro[Daglig] +
<<datasett-tilgangsnivå, Tilgangsnivå>>: https://op.europa.eu/s/pirq[Offentlig] +
<<datasett-distribusjon, Distribusjon>>: +https://example.org/eksempeldata.csv+ (_NB! dummy-URL som ikke virker_) +
<<datasett-kontaktpunkt, Kontaktpunkt>>: Direktoratet for eksempler, +data@direks.eks+ (_NB! dummy-e-postadresse som ikke virker_) +
<<datasett-språk, Språk>>: https://op.europa.eu/s/piq1[Norsk bokmål] +
****

.Teknisk veiledning

Eksemplet ovenfor i RDF Turtle:
-----
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix vcard: <http://www.w3.org/2006/vcard/ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix : <https://example.org/> .

<https://example.org/eksempeldata> a dcat:Dataset ;
  ### obligatoriske egenskaper:
    dct:identifier "https://example.org/eksempeldata"^^xsd:anyURI ; # identifikator
    dct:title "Eksempeldatasett"@nb ; # tittel
    dct:publisher <https://organization-catalogue.fellesdatakatalog.digdir.no/organizations/999999999> ; # utgiver, med dummy-org.nr.
    dct:description "Datasett med testdata"@nb ;
    dcat:theme <http://publications.europa.eu/resource/authority/data-theme/GOVE> ; # tema, Forvaltning og offentlig sektor
  ### anbefalte egenskaper:
    dct:subject <http://publications.europa.eu/resource/authority/dataset-type/TEST_DATA> ; # begrep, 'testdata'
    dct:spatial <http://publications.europa.eu/resource/authority/country/NOR> ; # dekningsområde, Norge
    dct:accrualPeriodicity <http://publications.europa.eu/resource/authority/frequency/DAILY> ; # frekvens, daglig oppdatering
    dct:accessRights <http://publications.europa.eu/resource/authority/access-right/PUBLIC> ; # tilgangsnivå, offentlig
  ### valgfrie egenskaper:
    dct:language <http://publications.europa.eu/resource/authority/language/NOB> ; # språk, norsk bokmål
    dcat:contactPoint [ a vcard:Organization ; # kontaktpunkt, med dummy data
       vcard:hasEmail <mailto:eks@direks.eks> ; # e-post
       vcard:organization-unit "Direktoratet for eksempler" ; # navn
       ] ;
  dcat:distribution [ a dcat:Distribution ; # distribusjon, med dummy data
    ### obligatoriske egenskaper:
      dcat:accessURL <https://example.org/eksempeldata.csv> ; # tilgangsURL, med dummy URL
    ### anbefalte egenskaper:
      dct:license <http://publications.europa.eu/resource/authority/licence/CC_BY_4_0> ; # lisens
    ] ;
  .
-----

=== Obligatoriske egenskaper i en datasettbeskrivelse [[datasett-obligatoriske-egenskaper]]

Som et minimum skal følgende tas med i en datasettbeskrivelse:

* Datasett - beskrivelse: beskrivelse av datasettet.
* Datasett - identifikator: identifikator til datasettet.
* Datasett - tema: tema som datasettet kan sorteres under.
* Datasett - tittel: navnet på datasettet.
* Datasett - utgiver: aktør (organisasjon) ansvarlig for å gjøre datasettet tilgjengelig.

==== Datasett - beskrivelse [[datasett-beskrivelse]]

// .Anbefalinger

For at andre skal kunne vite hva slags datasett du har, skal du oppgi en kort og presis beskrivelse av datasettet.

 * Beskrivelsen skal være kortfattet slik at lister over datasett forståes ved å lese de første linjene.
 * Hensikten med datasettet bør komme fram (f.eks. “Løsøreregisteret inneholder tinglyste flyttbare eiendeler”).
 * Beskriv hva datasettet inneholder. Hvilke opplysninger som utgjør kjernen i datasettet bør angis.
 * Feltinnhold skal ikke listes her i beskrivelsen, men i <<datasett-emneord, Datasett - emneord>> eller <<datasett-begrep, Datasett - begrep>>.
 * Beskrivelsen er ikke en gjentakelse av <<datasett-tittel, Datasett - tittel>>.
 * Bruk folkelige ord (f.eks. “Løsøre” forklares som “flyttbare eiendeler (Løsøre)”, ev. bare folkelige uttrykk mens faguttrykket tas med som <<datasett-emneord, Datasett - emneord>> slik at det gir treff i søk).
 * Beskriv avgrensninger, hva datasettet ikke inneholder, dersom dette kan misforstås ut fra tittelen.
 * Begrens bruk av lenker og markup (formatering) i teksten. Skal man angi språk må teksten formelt sett være fri for lenker og formatering (HTML).

.Eksempler

* [ ] [line-through]#“Løsøreregisteret inneholder løsøre med unntak av skip og luftfartøy”#
Et lite folkelig ord (løsøre) er brukt. Avgrensningene her er greie.

* [ ] [line-through]#“Løsøreregisteret inneholder tinglyste flyttbare eiendeler som biler og båter”#
Hva som inngår i datasettet er godt beskrevet, men unntakene her er utelatt.

* [*] “Løsøreregisteret inneholder tinglyste flyttbare eiendeler med unntak av skip og luftfartøy”

.Teknisk veiledning
Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-beskrivelse[Datasett: beskrivelse (`dct:description`) i DCAT-AP-NO].

* Der målform er kjent skal språkkoden "nb" (bokmål) eller "nn" (nynorsk) brukes, "no" (norsk) brukes ellers.

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:description "Løsøreregisteret inneholder tinglyste flyttbare eiendeler med unntak av skip og luftfartøy"@nb .
----

==== Datasett - identifikator [[datasett-identifikator]]

For å kunne referere til et datasett er det nødvendig å tilordne datasettet en identifikator. Identifikatoren er som regel systemgenerert av verktøyet som brukes til å beskrive et datasett, slik at du som vanlig bruker ikke trenger å oppgi verdien til denne egenskapen manuelt.

.Teknisk veiledning
Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-identifikator[Datasett: identifikator (`dct:identifier`) i DCAT-AP-NO], se <<om-identifikator, Om identifikator (`dct:identifier`)>>.

==== Datasett - tema [[datasett-tema]]

// .Anbefaling

For å kunne sortere datasettet inn under gitte kategorier er det nødvendig å tilordne "tema" til datasettet.

 * Ett eller flere temaer skal velges fra https://op.europa.eu/s/oZjL[EUs kontrollerte liste over temaer].

 * Ett eller flere temaer bør velges fra https://psi.norge.no/los/struktur.html[den norske LOS].

.Eksempler

* [*] *Helse* (`HEAL` fra EU-listen)
* [*] *Helsestasjon* (`helsestasjon` fra LOS)

.Teknisk veiledning
Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-tema[Datasett: tema (`dcat:theme`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dcat:theme <http://publications.europa.eu/resource/authority/data-theme/HEAL> , # helse
    <https://psi.norge.no/los/ord/helsestasjon> . # helsestasjon
----

==== Datasett - tittel [[datasett-tittel]]

// .Anbefalinger

For at andre lett skal kunne se hva datasettet ditt omhandler når datasettet f.eks. er listet opp blant mange andre datasett, er det nødvendig å gi datasettet ditt en tittel.

* Tittelen skal være kortfattet, kunne stå alene og gi mening.
 * Organisasjonens navn trenger ikke å være med, med mindre det er spesielt relevant for datasettets innholdsmessige utvalg.
 * Tittelen skal gjenspeile avgrensninger dersom datasettet er avgrenset i populasjonen -  populasjonen er avgrenset av geografi eller formål, f.eks. “... med støtte i Lånekassen”, “... i Oslo”, “Folketellingen av 1910”. Der populasjonen ikke er avgrenset angis IKKE dette (f.eks. valgkrets)
 * Forkortelser skal skrives helt ut (DTM10 erstattes av “Digital Terrengmodell 10m oppløsning (DTM10)” . Bruk eventuelt <<datasett-emneord, Datasett - emneord>> til forkortelser. Målgruppen er personer som ønsker å finne relevante datasett raskt, unngå derfor interne navn eller forkortelser i tittel. I det offentlige opererer man ofte med flere titler eller navn på ting. Et datasett kan ha et offisielt navn, et kortnavn og en forkortelse. For eksempel: Datasettet “Administrative enheter i Norge” har ABAS som forkortelse. Det er sjelden man bruker den fulle tittelen, så for å gjøre et datasett mest mulig søkbart er det behov for at man kan registrere kortnavn, forkortelser og/eller alternative titler.
 * Lov- eller forskriftshjemlede navn bør brukes i tittel (f.eks. Jegerregisteret)

.Eksempler

 * [*] “Bomstasjoner i Norge”
* [ ] [.line-through]#“Statens vegvesens oversikt over Bomstasjoner i Norge”#

* [*] “Digital Terreng Modell 10m oppløsning (DTM10)”
* [ ] [.line-through]#“DTM10”#

.Teknisk veiledning
Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-tittel[Datasett: tittel (`dct:title`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
-----
<etDatasett> a dcat:Dataset ;
  dct:title "Bomstasjoner i Norge"@nb .
-----

==== Datasett - utgiver [[datasett-utgiver]]

// .Anbefalinger

For at andre lett skal kunne se hvem som er ansvarlig for at datasettet ditt _er_ tilgjengelig (ikke nødvendigvis samme som den som faktisk gjør datasettet tilgjengelig), er det nødvendig å oppgi utgiver.

 * Skal peke på en virksomhet (juridisk person, organisasjonsledd, underenhet).
 * Utgiveren av datasettet forvalter sammensetning av dataene, altså datasettet, og ikke nødvendigvis selve dataene.

.Eksempler
* [*] Arbeids- og velferdsetaten

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-utgiver[Datasett: utgiver (`dct:publisher`) i DCAT-AP-NO].

Inntil https://data.brreg.no tilbyr RDF-baserte metadata basert på organisasjonsnummeret (orgnummer), skal følgende mønster benyttes: `+https://organization-catalogue.fellesdatakatalog.digdir.no/organizations/{orgnummer}+`.

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:publisher <https://organization-catalogue.fellesdatakatalog.digdir.no/organizations/889640782> . #NAV
----



=== Anbefalte egenskaper i en datasettbeskrivelse [[datasett-anbefalte-egenskaper]]

Følgende opplysninger bør du ta med i en datasettbeskrivelse hvis de finnes:

* Datasett - begrep: begrep som er viktig for å forstå og tolke datasettet.
* Datasett - ble generert ved: aktivitet ved hvilken datasettet ble generert.
* Datasett - datasettdistribusjon: tilgjengelig distribusjon av datasettet.
* Datasett - dekningsområde: geografisk område dekket av datasettet.
* Datasett - emneord: emneord (søkeord) dekket av datasettet.
* Datasett - følger: regelverk som datasettet følger.
* Datasett - kontaktpunkt: kontaktpunkt ved spørsmål om datasettet.
* Datasett - tidsrom: tidsrom dekket av datasettet.
* Datasett - tilgangsnivå: i hvilken grad datasettet kan bli gjort tilgjengelig.

==== Datasett - begrep [[datasett-begrep]]

// .Anbefalinger

For at andre lett skal kunne forstå typer innhold i datasettet ditt, skal du knyttet datasettet til relevante begrepsdefinisjoner _hvis_ de finnes.

 * Innholdstyper i datasettet beskrives med referanse til begreper i begrepskatalog.
 * Dersom det ikke kan benyttes en begrepskatalog brukes <<datasett-emneord, Datasett - emneord>>.


.Eksempler

* [*]  [.underline]#Løsøre#, [.underline]#Pant#, [.underline]#Tinglysing#


.Ytterligere anbefalinger
Et datasett bør knyttes til de aktuelle og sentrale begrepene i en begrepskatalog. Ved å henvise til gjennomarbeidede definisjoner som forvaltes av din virksomhet eller andre, sikrer vi at det er tydelig hvordan et begrep brukt i datasettet skal forstås og at denne forståelsen til en hver tid er riktig og oppdatert. Vi ønsker at alle datasettene skal ha lenker til de aktuelle begrepene i virksomhetens katalog, slik at det er tydelig definert hva begrepene innebærer.

I https://www.digdir.no/digitalisering-og-samordning/referansekatalogen-it-standardar/1480[Referansekatalogen] finner du relevante https://www.digdir.no/digitalisering-og-samordning/omgrepsanalyse-og-definisjonsarbeid/1483[forvaltningsstandarder for bruksområdet "Begrepsanalyse og definisjonsarbeid"].

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-begrep[Datasett: begrep (`dct:subject`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:subject <http://brreg.no/begrepskatalog/begep/løsøre>,
              <http://brreg.no/begrepskatalog/begep/pant>,
              <http://brreg.no/begrepskatalog/begep/tingslysning> .
----

==== Datasett - ble generert ved [[datasett-bleGenerertVed]]

// .Anbefalinger
Hvilken type aktivitet dine data ble generert ved, kan ha betydning for dem som skal vurdere gjenbruk/viderebruk av dine data. Du skal derfor oppgi dette _hvis_ det er mulig.

Det anbefales å bruke en av følgende verdier:

* `ved vedtak`: datasettet ble generert som et resultat / ifm. et vedtak. Eksempel: skatteoppgjør.
* `ved innhenting fra tredjepart`: datasettet ble hentet inn fra en tredjepart. Eksempel: preutfylt skattemelding.
* `ved innhenting fra brukeren`: datasettet ble generert på grunnlag av data fra brukeren. Eksempel: innlevert skattemelding.

.Eksempler:
* [*] ved vedtak

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-bleGenerertVed[Datasett: ble generert ved (`prov:wasGeneratedBy`)] i DCAT-AP-NO.

Følgende predefinerte instanser av `prov:Activity` skal brukes:

* ved vedtak: `provno:administrativeDecision`
* ved innhenting fra tredjepart: `provno:collectingFromThirdParty`
* ved innhenting fra brukeren: `provno:collectingFromUser`

Eksempel i RDF Turtle:
----
@prefix provno: <https://data.norge.no/vocabulary/provno#> .

<etDatasett> a dcat:Dataset ;
   prov:wasGeneratedBy provno:administrativeDecision . # vedtak
----

==== Datasett - datasettdistribusjon [[datasett-datasettdistribusjon]]

// .Anbefalinger

_Hvis_ datasettet ditt er gjort tilgjengelig skal du beskrive hvor det faktiske datasettet finnes (f.eks. hvor datafilen kan lastes ned), slik at andre skal kunne få tak i datasettet ditt.

 * Det angis i utgangspunktet en distribusjon per fil, feed eller API
 * Dersom det er ett API som leverer flere filformater angis det som en distribusjon
 * Se også under <<sammenheng, Sammenheng mellom datasett, begrep, distribusjon, datatjeneste og informasjonsmodell>>

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-datasettdistribusjon[Datasett: datasettdistribusjon (`dcat:distribution`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
    dcat:distribution <enDistribusjon> . # refererer til en beskrivelse av en distribusjon
----

==== Datasett - dekningsområde [[datasett-dekningsområde]]

// .Anbefalinger
_Hvis_ datasettet ditt kun har innhold fra visse geografiske områder, skal du oppgi dette. Datasettet “Observert hekking av grågås i Oppdal” har f.eks. kommune Oppdal som sitt geografiske dekningsområde.

 * Minst en av verdiene skal være fra kontrollerte vokabularer https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/continent[Continent], https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/country[Country], https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/place[Place] eller http://sws.geonames.org/[GenNames].
 * https://data.geonorge.no/administrativeEnheter/nasjon/doc/173163[Administrative enheter] fra Kartverket bør brukes for å angi geografiske områder i Norge.
  * Flere områder kan angis om relevant.

.Eksempler

* [*] [.underline]#Norge# (lenke: http://publications.europa.eu/resource/authority/country/NOR)
* [*] [.underline]#Oppdal# (lenke: https://data.geonorge.no/administrativeEnheter/kommune/id/172879)

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-dekningsomr%C3%A5de[Datasett: dekningsområde (`dct:spatial`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
   dct:spatial <http://publications.europa.eu/resource/authority/country/NOR> , # Norge
      <https://data.geonorge.no/administrativeEnheter/kommune/id/172879> ; # Oppdal
   .
----

==== Datasett - emneord [[datasett-emneord]]

// .Anbefalinger
Ord og uttrykk som hjelper brukeren til å finne datasettet og som ikke kan knyttes til publiserte begrepsdefinisjoner, inkluderes som emneord.

 * Angi synonymer til hjelp i søk
 * Angi sentralt innhold i datasettet som ikke finnes begrepsdefinisjoner for ennå

.Eksempler

* [*] uførepensjon, uførepensjonister, uførereform

.Teknisk veiledning
Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-emneord[Datasett: emneord (`dcat:keyword`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dcat:keyword "uførepensjon"@nb, "uførepensjonister"@nb, "uførereformen"@nb .
----

==== Datasett - følger [[datasett-følger]]

// .Anbefalinger

_Hvis_ (oppretting og/eller forvaltning av) datasettet ditt følger gitte regelverk, skal det opplyses om.

* Angi referanse til regelverk som datasettet følger, og derfra referanse til ev. lovhjemmel.

.Eksempler
* [*] Regel for skjerming, med lenke til lovhjemmel.
* [*] Regel for utlevering, med lenke til lovhjemmel.
* [*] Behandlingsgrunnlag, med lenke til lovhjemmel.

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-f%C3%B8lger[Datasett: følger (`cpsv:follows`) i DCAT-AP-NO].

Det er predefinerte instanser av `cpsv:Rule` for hhv. skjermingsregel (`cpsvno:ruleForNonDisclosure`), utleveringsregel (`cpsvno:ruleForDisclosure`) og behandlingsgrunnlag (`cpsvno:ruleForDataProcessing`), som bør brukes ved angivelse av de aktuelle typer regelverk.

Eksempel i RDF Turtle:
----
@prefix cpsvno: <https://data.norge.no/vocabulary/cpsvno#> .

<etDatasett> a dcat:Dataset ;
  cpsv:follows [ a cpsv:Rule ;
        dct:type cpsvno:ruleForNonDisclosure ; # skjermingsregel
        cpsv:implements [ a eli:eli:LegalResource ; # regulativ ressurs
              dct:type <lov> ; # type ressurs (obligatorisk egenskap)
              rdfs:seeAlso "https://lovdata.no/NL/lov/2016-05-27-14/§3-1" ; # referanse
              dct:title "Skatteforvaltningsloven §3-1"@nb ; # tittel
        ] ;
      ] , [ a cpsv:Rule ;
          dct:type cpsvno:ruleForDisclosure ; # utleveringsregel
          cpsv:implements [ a eli:LegalResource ; # regulativ ressurs
                dct:type <lov> ; # type ressurs (obligatorisk egenskap)
                rdfs:seeAlso "https://lovdata.no/NL/lov/2016-05-27-14/§3-3" ; # referanse
                dct:title "Skatteforvaltningsloven §§ 3-3 til 3-9"@nb ; # tittel
          ] ;
        ] , [ a cpsv:Rule ;
            dct:type cpsvno:ruleForDataProcessing ; # behandlingsgrunnlag
            cpsv:implements [ a eli:LegalResource ; # regulativ ressurs
                dct:type <lov> ; # type ressurs (obligatorisk egenskap)
                rdfs:seeAlso "https://lovdata.no/NL/lov/2016-05-27-14/§3-3" ; # referanse
                dct:title "Skatteforvaltningsloven §§ 3-3 til 3-9"@nb ; # tittel
            ] ;
          ] ;
    .

<lov> a skos:Concept , eli:ResourceType ; # ressurstype 'lov'
  skos:prefLabel "lov"@nb ; # anbefalt term
  skos:definition "rettsregler som fastsetter rettigheter og plikter"@nb ; # definisjon
  .
----

NOTE: https://data.norge.no/specification/dcat-ap-no/#RegulativRessurs-referanse[Kommentaren til `rdfs:seeAlso` i DCAT-AP-NO] sier "for referanse til Lovdata bør ELI-URI brukes". I RDF-eksemplet ovenfor er https://lovdata.no/eli/[ELI-URI] imidlertid ikke brukt. Dette fordi det p.t. ikke er knyttet funksjonalitet til ELI-URI for henvisninger til deler av en lov, f.eks. §3-3. Det vil si at det for øyeblikket er mulig å henvise til deler ved å bruke ELI, f.eks. https://lovdata.no/eli/lov/2016/05/27/14/nor/section/3-3, men oppslaget vil lede til en hel lov og ikke til §3-3.

==== Datasett - kontaktpunkt [[datasett-kontaktpunkt]]

// .Anbefalinger
For at andre skal kunne kontakte utgiveren av et datasett, bør kontaktinformasjonen til utgiveren oppgis.


 * Angi kontaktinformasjonen som kan brukes ved henvendelser om et datasett.
 * Vi anbefaler sterkt å bruke organisatoriske enheter og ikke enkeltpersoner som kontaktpunkt.

.Eksempler

* [*] Opplysningsavdelingen, Brønnøysundregistrene

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-kontaktpunkt[Datasett: kontaktpunkt (`dcat:contactPoint`) i DCAT-AP-NO].

https://www.w3.org/TR/vcard-rdf[Vcard] benyttes for å beskrive kontaktpunktet.

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ; # datasett
   dcat:contactPoint [ a vcard:Organization ; # kontaktpunkt
      vcard:hasEmail <mailto:OA-fagstillinger@brreg.no> ; # e-post
      vcard:organization-unit  "Opplysningsavdelingen, Brønnøysundregistrene" ; # navn
      ] .
----

==== Datasett - tidsrom [[datasett-tidsrom]]

// .Anbefalinger

_Hvis_ innholdet i et datasett dekker et avgrenset tidsrom, skal dette opplyses om.

 * Angi tidsmessig  avgrensning dersom datasett kun har innhold fra visse perioder. For mange datasett knyttet til registerfunksjoner vil tidsrom være direkte koblet mot oppdateringsfrekvens. For andre datasett vil tidsrom være vesentlig i forhold til forståelse av bruk av dataene, f.eks. folketellinger.
 * Dersom det er angitt en periode med årstall, tolkes dette som fra og med 1. januar første år til og med 31. desember siste år.
 * Ved ett årstall på begynnelse, men ikke angitt slutt, tolkes det at datasettet har data også i en ubestemt fremtid og tilsvarende om startdatoen mangler antas det at det er ikke angitt om datasettet har en start.
 * Dersom datasettet er en av flere i en tidsserie anbefales det at det lages et overordnet datasett for tidsserien uten distribusjoner som peker på hvert datasett. Se også under <<beskrivelse-av-datasettserie, Beskrivelse av tidsserie/datasettserie>>.
 * Det benyttes tidsstempel for registreringen av første og siste dataelement i datasettet.
 * Det kan angis flere tidsperioder per datasett, men det anbefales at periodene ikke er overlappende.


.Eksempler

* [*] “1901”

.Teknisk veiledning
Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-tidsrom[Datasett: tidsrom (dct:temporal) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:temporal  [ a dct:PeriodOfTime ;
    dcat:startDate "1901-01-01"^^xsd:date ;
    dcat:endDate "1901-12-31"^^xsd:date ;
   ] .
----

==== Datasett - tilgangsnivå [[datasett-tilgangsnivå]]


// .Anbefalinger

Uansett om datasettet ditt er gjort tilgjengelig eller ikke, bør du oppgi i hvilken grad datasettet kan bli gjort tilgjengelig for allmennheten, såkalt tilgangsnivå.

 * Angi om datasettet er helt eller delvis skjermet for innsyn, ved å bruke en av verdiene fra EU sitt kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/access-right[Access right]: f.eks. "offentlig" (`PUBLIC`).

 * Skal gjenspeile det mest begrensede feltet/opplysningen i datasettet.

 * Varianter av datasettet kan være offentlig ved at det utelater de felt som gjør at det opprinnelige datasettet er begrenset teller unntatt offentlighet.
 * Ved bruk av verdiene "begrenset offentlighet" og "unntatt offentlighet" er egenskapen <<datasett-følger, Datasett - følger>> anbefalt.

.Eksempler
Enhetsregisteret (hele):

* [*] begrenset offentlighet

Enhetsregisteret - Juridisk person (hovedenhet):

* [*] offentlig

.Teknisk veiledning
Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-tilgangsniv%C3%A5[Datasett: tilgangsnivå (`dct:accessRights`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dcat:accessRights <http://publications.europa.eu/resource/authority/access-right/PUBLIC> .
----

=== Valgfrie egenskaper i en datasettbeskrivelse [[datasett-valgfrie-egenskaper]]

I tillegg til obligatoriske (skal brukes) og anbefalte (bør brukes) egenskaper, er det en del egenskaper som er valgfrie (kan brukes) i en datasettbeskrivelse:

* Datasett - annen identifikator: sekundær identifikator til datasettet.
* Datasett - dokumentasjon: referanse til side eller dokument som beskriver datasettet ytterligere.
* Datasett - eksempeldata: referanse til eksempeldata av datasettet.
* Datasett - endringsdato: dato for siste oppdatering av datasettet.
* Datasett - er del av: datasett som dette datasettet er en del av.
* Datasett - er påkrevd av: datasett som er avhengig av dette datasettet.
* Datasett - er referert av: datasett som refererer til dette datasettet.
* Datasett - er versjon av: datasett som dette datasettet er en versjon av.
* Datasett - erstatter: datasett som dette datasettet erstatter.
* Datasett - erstattes av: datasett som er erstattet av dette datasettet.
* Datasett - frekvens: oppdateringsfrekvens av innholdet i datasettet.
* Datasett - har del: datasett som inngår i dette datasettet.
* Datasett - har kvalitetsnote: tekstlig beskrivelse av kvalitet på datasettet.
* Datasett - har måleresultat: kvantifiserbar beskrivelse av kvalitet på datasettet.
* Datasett - har versjon: datasett som er versjon av dette datasettet.
* Datasett - i samsvar med: standard/spesifikasjon (inkl. informasjonsmodell) som datasettet er i samsvar med.
* Datasett - kilde: datasett som dette datasettet er avledet fra.
* Datasett - krever: datasett som dette datasettet er avhengig av.
* Datasett - kvalifisert kreditering: aktør som har en eller annen form for ansvar for datasettet.
* Datasett - kvalifisert relasjon: beslektet ressurs (f.eks. en publikasjon)
* Datasett - landingsside: nettside som gir tilgang til datasettet, tilleggsinfo om datasettet etc.
* Datasett - opphav: beskrivelse av endring i eierskap og forvaltning av datasettet.
* Datasett - produsent: aktør som har produsert datasettet.
* Datasett - refererer til: en annen ressurs som kan være nyttig for brukere av datasettet å være oppmerksom på.
* Datasett - relatert ressurs: annen beslektet ressurs.
* Datasett - romlig oppløsning: minst romlig oppløsning for datasettet.
* Datasett - språk: språk datasettet er på.
* Datasett - tidsoppløsning: miste oppløsning i tidsperiode i datasettet.
* Datasett - type: datasettets type.
* Datasett - utgivelsesdato: dato for den formelle utgivelsen av datasettet.
* Datasett - versjon: versjonsnummer eller annen versjonsbetegnelse for datasettet.
* Datasett - versjonsnote: beskrivelse av forskjellene mellom denne og en tidligere versjon av datasettet.

Ikke alle valgfrie egenskaper er beskrevet i etterfølgende avsnitt. Se under <<hensikt-og-avgrensing, Hensikt og avgrensning>> for hvordan du kan melde inn behov for beskrivelser.

==== Datasett - annen identifikator [[datasett-annenIdentifikator]]

_<ikke beskrevet, tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-annenIdentifikator[Datasett: annen identifikator (`adms:identifier`) i DCAT-AP-NO]>_

==== Datasett - dokumentasjon [[datasett-dokumentasjon]]

// .Anbefalinger
Utdypende dokumentasjon av datasettet angis ved å peke på en side der den finnes.

.Eksempler

* [*] https://confluence.brreg.no/display/DBNPUB/Informasjonsmodell+for+Enhetsregisteret+og+Foretaksregisteret

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-dokumentasjon[Datasett: dokumentasjon (`foaf:page`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  foaf:page <https://confluence.brreg.no/display/DBNPUB/Informasjonsmodell+for+Enhetsregisteret+og+Foretaksregisteret> .
----

==== Datasett - eksempeldata [[datasett-eksempeldata]]


// .Anbefalinger
Benyttes for å gi eksempeldata for et datasett, og hvordan en faktisk distribusjon ser ut.

 * Dersom datasettet inneholder personopplysninger vil det være nyttig for bruker å se et eksempeldatasett som f.eks. viser en anonymisert rad i datasettet.

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-eksempeldata[Datasett: eksempeldata (`adms:sample`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  adms:sample <distribusjonAvEksempeldata> .

<distribusjonAvEksempeldata> a dcat:Distribution ;
  dcat:accessURL <https://example.org/eksempeldata.csv> .
----

==== Datasett - endringsdato [[datasett-endringsdato]]

// .Anbefalinger

For at andre skal kunne vite når datasettet sist ble oppdatert angis tidspunkt for siste endring.

 * Tidspunktet angir når innholdet i datasettet sist er endret.

.Eksempler

* [*] 01.01.2017

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-endringsdato[Datasett: endringsdato (`dct:modified`) i DCAT-AP-NO].

* Angis som dato (`xsd:date`) eller tidspunkt (`xsd:dateTime`).

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:modified "2017-01-01"^^xsd:date .
----

==== Datasett - er del av [[datasett-erDelAv]]

// .Anbefalinger

Brukes til å angi at det aktuelle datasettet er en delmengde at et annet datasett.

 * Der registre oppdeles i mindre datasett skal relasjonen brukes. F.eks. er datasettet Underenheter er del av datasettet Enhetsregisteret.
 * Den motsatte relasjonen <<datasett-harDel, Datasett - har del>> brukes til å uttrykke at et datasett består av andre datasett.

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-erDelAv[Datasett: er del av (`dct:isPartOf`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<underenheter> a dcat:Dataset ;
  dct:isPartOf <enhetsregisteret> .

<enhetsregisteret> a dcat:Dataset .
----

==== Datasett - er påkrevd av [[datasett-erPåkrevdAv]]

// .Anbefalinger
Brukes til å referere til annet datasett som det aktuelle datasettet er nødvendig for.

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-erP%C3%A5krevdAv[Datasett: er påkrevd av (`dct:isRequiredBy`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<datasettA> a dcat:Dataset ;
  dct:isRequiredBy <datasettB> .

<datasettB> a dcat:Dataset .
----

==== Datasett - er referert av [[Datasett-erReferertAv]]

Motsatt av <<datasett-referererTil, Datasett - refererer til>>.

_<ikke beskrevet, tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-erReferertAv[Datasett: er referert av (`dct:isReferencedBy`) i DCAT-AP-NO]>_

==== Datasett - er versjon av [[datasett-erVersjonAv]]

// .Anbefalinger

Brukes til å referere til et annet datasett som det aktuelle datasettet er en versjon av.

 * I prinsippet det samme datasettet, men hvor innholdet er blitt oppdatert f.eks. på bakgrunn av bedret datakvalitet e.l.

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-erVersjonAv[Datasett: er versjon av (`dct:isVersionOf`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:isVersionOf <forrigeVersjon> .

<forrigeVersjon> a dcat:Dataset .
----

==== Datasett - erstatter [[datasett-erstatter]]

Motsatt av <<datasett-erstattesAv, Datasett - erstattes av>>.

_<ikke beskrevet, tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-erstatter[Datasett: erstatter (`dct:replaces`) i DCAT-AP-NO]>_

==== Datasett - erstattes av [[datasett-erstattesAv]]

// .Anbefalinger
Brukes til å referere til et datasett som erstatter dette datasettet.

 * F.eks. kan et kodeverk bli erstattet av en nyere utgave.

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-erstattesAv[Datasett: erstattes av (`dct:isReplacedBy`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:isReplacedBy <nyUtgave> .

<nyUtgave> a dcat:Dataset .
----

==== Datasett - frekvens [[datasett-frekvens]]

// .Anbefalinger
Brukes til å beskrive hvor ofte datasettet blir oppdatert.

 * Beskriv hvor ofte datasettet har nytt innhold. For eksempel oppdateres Enhetsregisteret med nye enheter og sletting av enheter _kontinuerlig_, mens Inntektsdata fra likningen (Skattemelding) er _årlig_ og Folketelling fra 1910 oppdateres _aldri_.
 * Begreper (og tilhørende URIer) fra EU sitt kontrollerte vokabular for https://op.europa.eu/s/o16S[Frequency] skal benyttes.

.Eksempler

* [*] Daglig

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-frekvens[Datasett: frekvens (`dct:accrualPeriodicity`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:accruralPeriodicity <http://publications.europa.eu/resource/authority/frequency/DAILY> .
----

==== Datasett - har del [[datasett-harDel]]

Motsatt av <<datasett-erDelAv, Datasett - er del av>>.

_<ikke beskrevet, tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-harDel[Datasett: har del (`dct:hasPart`) i DCAT-AP-NO]>_

==== Datasett - har kvalitetsnote [[datasett-harKvalitetsNote]]

Se under <<beskrivelse-av-kvalitet, Beskrivelse av kvalitet>>.

.Teknisk veiledning
Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-harKvalitetsnote[Datasett: har kvalitetsnote (`dqv:hasQualityAnnotation`) i DCAT-AP-NO].

==== Datasett - har måleresultat [[datasett-harMåleresultat]]

Se under <<beskrivelse-av-kvalitet, Beskrivelse av kvalitet>>.

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-harM%C3%A5leresultat[Datasett: har måleresultat (`dqv:hasQualityMeasurement`) i DCAT-AP-NO].

==== Datasett - har versjon [[datasett-harVersjon]]

_<ikke beskrevet, tilsvarer  https://data.norge.no/specification/dcat-ap-no/#Datasett-harVersjon[Datasett: har versjon (`dct:hasVersion`) i DCAT-AP-NO]>_

==== Datasett - i samsvar med [[datasett-iSamsvarMed]]

// .Anbefalinger

Brukes til å beskrive at et datasett er i henhold til gitt(e) standard(er)/spesifikasjon(er)/informasjonsmodell(er)/o.l.

Se under <<sammenheng, Sammenheng mellom datasett ... og informasjonsmodell>> for knytting av informasjonsmodell til datasett.

.Eksempler

Datasettet er i samsvar med "Produktspesifikasjon NVE flomsoner" som  innholdsstandard.

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-iSamsvarMed[Datasett: i samsvar med (`dct:conformsTo`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dcat:conformsTo [ a dct:Standard ;
  skos:prefLabel "Produktspesifikasjon NVE flomsoner 1.0"@nb ;
  rdfs:seeAlso <http://sosi.geonorge.no/Produktspesifikasjoner/Produktspesifikasjon_NVE_Flomsoner_1%200.pdf> ;
  ] .
----

==== Datasett - kilde [[datasett-kilde]]

// .Anbefalinger
Brukes til å referere til et datasett som helt eller delvis er en kilde til dette datasettet.

 * Peker til datasettet som helt eller delvis er en kilde for det aktuelle datasettet.
 * Dersom et åpent datasett er basert på et annet hvor personopplysninger er fjernet, kan relasjonen brukes.
 * Et datasett som er avledet fra et annet skal ha en referanse til kilde for det aktuelle datasettet.
 * Dersom det er et utvalg fra et annet datasett bør heller <<datasett-erDelAV, Datasett - er del av>> brukes.

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-kilde[Datasett: kilde (`dct:source`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dcat:source <kildeDatasett> .

<kildeDatasett> a dcat:Dataset .
----

==== Datasett - krever [[datasett-krever]]

Motsatt av <<datasett-erPåkrevdAv, Datasett: er påkrevd av>>.

_<tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-krever[Datasett: krever (`dct:requires`) i DCAT-AP-NO]>_

==== Datasett - kvalifisert kreditering [[datasett-kvalifisertKreditering]]

_<ikke beskrevet, tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-kvalifisertKreditering[Datasett: kvalifisert kreditering (`prov:qualifiedAttribution`) i DCAT-AP-NO]>_


==== Datasett - kvalifisert relasjon [[datasett-kvalifisertRelasjon]]

_<ikke beskrevet, tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-kvalifisertRelasjon[Datasett: kvalifisert relasjon (`dcat:qualifiedRelation`) i DCAT-AP-NO]>_

==== Datasett - landingsside [[datasett-landingsside]]

// .Anbefalinger

Brukes til å referere til en side med dokumentasjon om datasettet, som kan beskrive datasettets innhold og struktur, og tilgang. Det anbefales at landingsside brukes der man refererer til utfyllende dokumentasjon, og <<datasett-datasettdistribusjon, Datasett - datasettdistribusjon>> benyttes f.eks. når man vil referere til en søkeside.

 * kan referere til datasettets hjemmeside
 * kan referere til en samleside som beskriver innhold og struktur
 * kan referere til en samleside om nedlasting/bruk/søk (tjenestene)
 * det kan refereres til flere sider

.Eksempler

* [*] https://confluence.brreg.no/display/DBNPUB/Informasjonsmodell+for+Enhetsregisteret+og+Foretaksregisteret

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-landingsside[Datasett: landingsside (`dcat:landingPage`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dcat:landingpage <https://www.brreg.no/om-oss/samfunnsoppdraget-vart/registera-vare/einingsregisteret/> .
----

==== Datasett - opphav [[datasett-opphav]]

_<ikke beskrevet, tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-opphav[Datasett: opphav (`dct:provenance`) i DCAT-AP-NO]>_

==== Datasett - produsent [[datasett-produsent]]

Brukes til å angi produsent(er) av datasettet der dette er en annen enn utgiver (<<datasett-utgiver, Datasett - utgiver>>).

 * Brukes unntaksvis der datasettet er satt sammen av data som andre har produsert.
 * Der produsent er en sammensatt gruppe, vil det ikke være mulig å bruke organisasjonsnummer. I så fall kan produsent oppgis som en instans av `foaf:Agent`.

.Eksempler

* [*] “Samarbeidskommunene A, B og C”

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-produsent[Datasett: produsent (`dct:creator`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:creator <samarbeidskommunene> .

<samarbeidskommunene> a foaf:Agent ;
  foaf:name "Samarbeidskommunene A, B og C" .
----


==== Datasett - refererer til [[datasett-referererTil]]

// .Anbefalinger
Her oppgir du referanse til andre ressurser som det kan være nyttig for brukere å være oppmerksom på.

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-referererTil[Datasett: refererer til (`dct:references`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:references [ a dcat:Resource ;
    dct:title "Register over offentlig støtte"@nb ;
    rdfs:seeAlso <http://brreg.no/catalogs/974760673/datasets/ca04abdd-6327-4833-bd05-7a3dca20e6a5> ] .
----

==== Datasett - relatert ressurs [[datasett-relatertRessurs]]

// .Anbefalinger
Her kan du angi referanser til andre ressurser (f.eks. andre datasett) som gir supplerende informasjon om innholdet i dette datasettet. Kan f.eks. være å relatere til et annet register.

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-relatertRessurs[Datasett: relatert ressurs (`dct:relation`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:relation <relatertDatasett> .

<relatertDatasett> a dcat:Dataset .
----

==== Datasett - romlig oppløsning [[datasett-romligOppløsning]]

_<ikke beskrevet, tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-romligOppl%C3%B8sning[Datasett: romlig oppløsning  (`dcat:spatialResolutionInMeters`) i DCAT-AP-NO]>_


==== Datasett - språk [[datasett-språk]]

// .Anbefalinger
Her kan du oppgi hvilket språk innholdet til datasettet har.

 * Det er hovedspråket benyttet i datasettets innhold som skal angis.
 * Er datasettet uten språklige tekster angis ikke språk.
 * Inneholder datasett tekster på flere språk, og det ikke er tydelig hva som er hovedspråket, angis ikke språk.

.Eksempler

* [*] Norsk bokmål

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-spr%C3%A5k[Datasett: språk (`dct:language`) i DCAT-AP-NO].

 * Språk angis ved å velge fra EUs kontrollerte liste over https://op.europa.eu/s/o19C[Language].

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:language <http://publications.europa.eu/resource/authority/language/NOB> . # Norsk bokmål
----

==== Datasett - tidsromsoppløsning [[datasett-tidsromsoppløsning]]

_<ikke beskrevet, tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-tidsoppl%C3%B8sning[Datasett: tidsoppløsning (`dcat:temporalResolution`) i DCAT-AP-NO]>_

==== Datasett - type [[datasett-type]]

// .Anbefalinger
Her kan du klassifisere datasettet ditt, f.eks. at datasettet er en kodeliste, slik at det blir mulig å gruppere datasettet ditt sammen med andre kodelister i f.eks. en katalog.

* EUs kontrollerte vokabular for https://op.europa.eu/s/o19R[Dataset type] bør brukes.

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-type[Datasett: type (`dct:type`) i DCAT-AP-NO].

Eksempel i RDF Turtle:
----
<ds1> a dcat:Dataset ;
  dct:type <http://publications.europa.eu/resource/authority/dataset-type/CODE_LIST> . # kodeliste

<ds2> a dcat:Dataset ;
  dct:type <http://publications.europa.eu/resource/authority/dataset-type/SYNTHETIC_DATA> . # kunstig data

<ds3> a dcat:Dataset ;
  dct:type <http://publications.europa.eu/resource/authority/dataset-type/TEST_DATA> . # testdata
----

==== Datasett - utgivelsesdato [[datasett-utgivelsesdato]]

// .Anbefalinger
Her kan du oppgi når datasettet er operativt og tilgjengelig.

* Angi når innholdet i datasettet gjøres tilgjengelig. Dette er ikke alltid  samsvarende med når den enkelte distribusjonen er tilgjengelig. Og heller ikke når beskrivelsen om datasettet utgis (katalogpostens utgivelse).

.Eksempler

* [*] 01.01.2017

.Teknisk veiledning

Dette tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-utgivelsesdato[Datasett: utgivelsesdato (`dct:issued`) i DCAT-AP-NO].

* Angis som xsd:date eller xsd:dateTime.

Eksempel i RDF Turtle:
----
<etDatasett> a dcat:Dataset ;
  dct:issued "2017-01-01"^^xsd:date .
----

==== Datasett - versjon [[datasett-versjon]]

_<ikke beskrevet, tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-versjon[Datasett: versjon (`owl:versionInfo`) i DCAT-AP-NO]>_

==== Datasett - versjonsnote [[datasett-versjonnote]]

_<ikke beskrevet, tilsvarer https://data.norge.no/specification/dcat-ap-no/#Datasett-versjonsnote[Datasett: versjonsnote (`adms:versionNotes`) i DCAT-AP-NO]>_
