== Beskrivelse av datasett [[beskrivelse-av-datasett]]

WARNING: [red yellow-background]#_NB! Hele kapittelet er under ferdigstilling._# +
[red yellow-background]#Innholdet i kapittelet er forholdsvis komplett.#

Se https://data.norge.no/guide/veileder-orden-i-eget-hus/[Veileder for orden i eget hus] for hvordan din virksomhet kartlegger hvilke datasett som skal beskrives. Denne veilederen beskriver videre hvordan datasett beskrives i henhold til forvaltningsstandarden https://data.norge.no/specification/dcat-ap-no/[DCAT-AP-NO v.2].

For at din beskrivelse av et datasett skal kunne nyttegjøres av andre, er det noen felter som skal/bør/kan fylles ut. I det følgende går vi gjennom de enkelte feltene og hvordan disse skal fylles ut.

=== Eksempel på en datasettbeskrivelse [[eksempel-datasettbeskrivelse]]

Under er et eksempel på en datasettbeskrivelse, med dummydata, hvor felter med * foran er obligatoriske:

****
*Tittel [https://data.norge.no/specification/dcat-ap-no/#Datasett-tittel[Datasett: tittel]]: Eksempeldatasett +
*Utgiver [https://data.norge.no/specification/dcat-ap-no/#Datasett-utgiver[Datasett: utgiver]]: Direktoratet for eksempler +
*Beskrivelse [https://data.norge.no/specification/dcat-ap-no/#Datasett-beskrivelse[Datasett: beskrivelse]]: Datasett med eksempeldata.
Formålet med dette datasettet er å illustrere hvordan et datasett skal/bør/kan beskrives iht. DCAT-AP-NO. +
*Tema [https://data.norge.no/specification/dcat-ap-no/#Datasett-tema[Datasett: tema]]: Offentlig forvaltning +
Begrep [https://data.norge.no/specification/dcat-ap-no/#Datasett-begrep[Datasett: begrep]]: +++<u>datasett</u>+++, +++<u>eksempeldata</u>+++ (med lenker til der begrepene er beskrevet) +
Dekningsområde [https://data.norge.no/specification/dcat-ap-no/#Datasett-dekningsomr%C3%A5de[Datasett: dekningsområde]]: Norge +
Oppdateringsfrekvens [https://data.norge.no/specification/dcat-ap-no/#Datasett-frekvens[Datasett: frekvens]]: Daglig +
Tilgangsnivå [https://data.norge.no/specification/dcat-ap-no/#Datasett-tilgangsniv%C3%A5[Datasett: tilgangsnivå]] : Offentlig +
Språk [https://data.norge.no/specification/dcat-ap-no/#Datasett-spr%C3%A5k[Datasett: språk]]: Norsk bokmål +
Kontaktpunkt [https://data.norge.no/specification/dcat-ap-no/#Datasett-kontaktpunkt[Datasett: kontaktpunkt]]: Direktoratet for eksempler, eks@direks.eks +
Distribusjon [https://data.norge.no/specification/dcat-ap-no/#Datasett-datasettdistribusjon[Datasett: datasettdistribusjon]]: +++<u>CSV</u>+++  (med lenke til csv-filen som inneholder dataene)
****

Se ellers https://data.norge.no/[Felles datakatalog] for konkrete eksempler på beskrivelser av virkelige datasett.

=== Obligatoriske felter i en datasettbeskrivelse [[datasett-obligatoriske-felter]]

Som et minimum skal følgende tas med i en datasettbeskrivelse:

* Datasett - beskrivelse: beskrivelse av datasettet.
* Datasett - identifikator: identifikator til datasettet.
* Datasett - tema: tema som datasettet kan sorteres under.
* Datasett - tittel: navnet på datasettet.
* Datasett - utgiver: aktør (organisasjon) ansvarlig for å gjøre datasettet tilgjengelig.

==== Datasett - beskrivelse [[datasett-beskrivelse]]

.Sammendrag
Beskrivelsen [https://data.norge.no/specification/dcat-ap-no/#Datasett-beskrivelse[Datasett: beskrivelse]] skal være kortfattet. Hensikten/formålet med datasettet bør komme fram. Hvilke opplysninger som utgjør kjernen i datasettet bør angis. Bruk folkelige ord. Beskriv avgrensninger, hva datasettet ikke inneholder. Begrens bruk av lenker og markup.

.Anbefalinger
En kort og presis beskrivelse av datasettet skal gjøre det lett for andre å se hva det inneholder.

 * Beskrivelsen skal være kortfattet slik at lister over datasett forståes ved å lese de første linjene.
 * Hensikten med datasettet bør komme fram (f.eks. “Løsøreregisteret inneholder tinglyste flyttbare eiendeler”).
 * Beskriv hva datasettet inneholder. Hvilke opplysninger som utgjør kjernen i datasettet bør angis.
 * Feltinnhold skal ikke listes, men listes i <<datasett-emneord, Datasett - emneord>> eller <<datasett-begrep, Datasett - begrep>>.
 * Beskrivelsen er ikke en gjentakelse av <<datasett-tittel, Datasett - tittel>>.
 * Bruk folkelige ord (f.eks. ”Løsøre” må forklares. F.eks. “flyttbare eiendeler (Løsøre)”, ev. bare folkelige uttrykk mens faguttrykket tas med som <<datasett-emneord, Datasett - emneord>> slik at det gir treff i søk).
 * Beskriv avgrensninger, hva datasettet ikke inneholder, dersom dette kan misforstås ut fra tittelen.
 * Begrens bruk av lenker og markup (formatering) i teksten. Skal man angi språk må teksten formelt sett være fri for lenker og formatering (HTML).
 * Der målform er kjent skal "nb" eller "nn" brukes, "no" brukes ellers.

.Eksempler

* [ ] [line-through]#“Løsøreregisteret inneholder løsøre med unntak av skip og luftfartøy”#
Et lite folkelig ord (løsøre) er brukt. Avgrensningene her er greie.

* [ ] [line-through]#“Løsøreregisteret inneholder tinglyste flyttbare eiendeler som biler og båter”#
Hva som inngår i datasettet er godt beskrevet, men unntakene her er utelatt.

* [*] “Løsøreregisteret inneholder tinglyste flyttbare eiendeler med unntak av skip og luftfartøy”

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dct:description "Løsøreregisteret inneholder tinglyste flyttbare eiendeler med unntak av skip og luftfartøy"@nb .
----

==== Datasett - identifikator [[datasett-identifikator]]

Identifikatoren [https://data.norge.no/specification/dcat-ap-no/#Datasett-identifikator[Datasett: identifikator]] er som regel systemgenerert av verktøyet som brukes til å beskrive et datasett, slik at du som vanlig bruker ikke trenger å fylle ut dette feltet manuelt.

For det som skal utvikle/tilpasse verktøystøtte, se under <<om-identifikator, Om identifikator (dct:identifier)>>.

==== Datasett - tema [[datasett-tema]]

.Sammendrag
Minst ett tema [https://data.norge.no/specification/dcat-ap-no/#Datasett-tema[Datasett: tema]] skal velges fra https://op.europa.eu/s/oZjL[den kontrollerte listen av EU-temaer].

.Anbefalinger
For å kunne sortere datasettet inn under gitte kategorier er det behov for tema

 * Ett eller flere temaer skal velges fra https://op.europa.eu/s/oZjL[den kontrollerte listen av EU-temaer].

 * Ett eller flere temaer bør velges fra https://psi.norge.no/los/struktur.html[den norske LOS].

.Eksempler

* [*] *Helse* (`HEAL` fra EU-listen)
* [*] *Helsestasjon* (`helsestasjon` fra LOS)

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dcat:theme <http://publications.europa.eu/resource/authority/data-theme/HEAL> , # helse
    <https://psi.norge.no/los/ord/helsestasjon> . # helsestasjon
----

==== Datasett - tittel [[datasett-tittel]]

.Sammendrag
Tittelen [https://data.norge.no/specification/dcat-ap-no/#Datasett-tittel[Datasett: tittel]] skal være kortfattet, kunne stå alene og gi mening. Organisasjonens navn trenger ikke å være med. Tittelen skal gjenspeile avgrensninger dersom datasettet er avgrenset i populasjonen. Forkortelser skal skrives helt ut.

.Anbefalinger
Datasettet har en tittel slik at det bl.a. kan vises i lister.

 * Tittelen skal være kortfattet, kunne stå alene og gi mening.
 * Organisasjonens navn trenger ikke å være med, med mindre det er spesielt relevant for datasettets innholdsmessige utvalg.
 * Tittelen skal gjenspeile avgrensninger dersom datasettet er avgrenset i populasjonen -  populasjonen er avgrenset av geografi eller formål, f.eks. “... med støtte i Lånekassen”, “... i Oslo”, “ Folketellingen av 1910”. Der populasjonen ikke er avgrenset angis IKKE dette (f.eks. valgkrets)
 * Forkortelser skal skrives helt ut (DTM10 erstattes av “Digital Terrengmodell 10m oppløsning (DTM10)” . Bruk eventuelt <<datasett-emneord, Datasett - emneord>> til forkortelser. Målgruppen er personer som ønsker å finne relevante datasett raskt, unngå derfor interne navn eller forkortelser i tittel. I det offentlige opererer man ofte med flere titler eller navn på ting. Et datasett kan ha et offisielt navn, et kortnavn og en forkortelse. For eksempel: Datasettet “Administrative enheter i Norge” har ABAS som forkortelse. Det er sjelden man bruker den fulle tittelen, så for å gjøre et datasett mest mulig søkbart er det behov for at man kan registrere kortnavn, forkortelser og/eller alternative titler.
 * Lov- eller forskriftshjemlede navn bør brukes i tittel (f.eks. Jegerregisteret)

.Eksempler

 * [*] “Bomstasjoner i Norge”
* [ ] [.line-through]#“Statens vegvesens oversikt over Bomstasjoner i Norge”#

* [*] “Digital Terreng Modell 10m oppløsning (DTM10)”
* [ ] [.line-through]#“DTM10”#

.Eksempel i RDF Turtle
-----
<etDatasett> a dcat:Dataset ;
  dct:title "Bomstasjoner i Norge"@nb .
-----

==== Datasett - utgiver [[datasett-utgiver]]

.Sammendrag
Utgiver [https://data.norge.no/specification/dcat-ap-no/#Datasett-utgiver[Datasett: utgiver]] skal peke på en virksomhet registrert i Enhetsregisteret.

.Anbefalinger
Identifisering av den aktøren som er ansvarlig for at datasettet _er_ tilgjengelig, ikke den som faktisk gjør datasettet tilgjengelig.

 * Skal peke på en virksomhet (juridisk person, organisasjonsledd, underenhet)
 * Det offisielle navnet på virksomheten vil hentes fra Enhetsregisteret, men kortform (f.eks. Digdir) kan legges inn av brukeren
 * Utgiveren av datasettet forvalter sammensetning av dataene, altså datasettet, og ikke nødvendigvis selve dataene.

.Eksempler
* [*] Arbeids- og velferdsetaten

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dct:publisher <https://organization-catalogue.fellesdatakatalog.digdir.no/organizations/889640782> . #NAV
----



=== Anbefalte felter i en datasettbeskrivelse [[datasett-anbefalte-felter]]

Følgende opplysninger bør du ta med i en datasettbeskrivelse hvis de finnes:

* Datasett - begrep: begrep som er viktig for å forstå og tolke datasettet.
* Datasett - ble generert ved: aktivitet ved hvilken datasettet ble generert.
* Datasett - datasettdistribusjon: tilgjengelig distribusjon av datasettet.
* Datasett - dekningsområde: geografisk område dekket av datasettet.
* Datasett - emneord: emneord (søkeord) dekket av datasettet.
* Datasett - følger: regelverk som datasettet følger.
* Datasett - kontaktpunkt: kontaktpunkt ved spørsmål om datasettet.
* Datasett - tidsrom: tidsrom dekket av datasettet.
* Datasett - tilgangsnivå: i hvilken grad datasettet kan bli gjort tilgjengelig.

==== Datasett - begrep [[datasett-begrep]]

.Sammendrag

Innholdstyper i datasettet beskrives med referanse til begreper [https://data.norge.no/specification/dcat-ap-no/#Datasett-begrep[Datasett: begrep]] i begrepskatalog.

.Anbefalinger

For å beskrive viktigste typer innhold i datasettet refereres det til begreper i begrepskataloger som også gir mulighet til å utnytte synonymer.

 * innholdstyper i datasettet beskrives med referanse til begreper i begrepskatalog
 * dersom det ikke kan benyttes en begrepskatalog brukes <<datasett-emneord, Datasett - emneord>>.

Et datasett skal lenke til de aktuelle og sentrale begrepene i en begrepskatalog. Ved å henvise til gjennomarbeidede definisjoner som virksomheten selv er ansvarlig for å vedlikeholde, sikrer vi at det er tydelig hvordan et begrep brukt i datasettet skal forstås og at denne forståelsen til en hver tid er riktig og oppdatert. Vi ønsker at alle datasettene skal ha lenker til de aktuelle begrepene i virksomhetens katalog, slik at det er tydelig definert hva begrepene innebærer

I https://www.digdir.no/digitalisering-og-samordning/referansekatalogen-it-standardar/1480[Referansekatalogen] finner du relevante https://www.digdir.no/digitalisering-og-samordning/omgrepsanalyse-og-definisjonsarbeid/1483[forvaltningsstandarder for bruksområdet "Begrepsanalyse og definisjonsarbeid"].


.Eksempler

* [*]  [.underline]#Løsøre#, [.underline]#Pant#, [.underline]#Tinglysing#

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dct:subject <http://brreg.no/begrepskatalog/begep/løsøre>,
              <http://brreg.no/begrepskatalog/begep/pant>,
              <http://brreg.no/begrepskatalog/begep/tingslysning> .
----

==== Datasett - ble generert ved [[datasett-bleGenerertVed]]

.Sammendag
For å angi hvilken aktivitet som genererte datasettet [https://data.norge.no/specification/dcat-ap-no/#Datasett-bleGenerertVed[Datasett: ble generert ved]].

.Anbefalinger
Det anbefales å bruke en av følgende verdier:

* `ved vedtak`: datasettet ble generert som et resultat / ifm. et vedtak. Eksempel: skatteoppgjør.
* `ved innhenting fra tredjepart`: datasettet ble hentet inn fra en tredjepart. Eksempel: preutfylt skattemelding.
* `ved innhenting fra brukeren`: datasettet ble generert på grunnlag av data fra brukeren. Eksempel: innlevert skattemelding.

For deg som skal utvikle/tilpasse verktøystøtte: Følgende predefinerte instanser av `prov:Activity` skal brukes:

* ved vedtak: `provno:administrativeDecision`
* ved innhenting fra tredjepart: `provno:collectingFromThirdparty`
* ved innhenting fra brukeren: `provno:collectingFromUser`

.Eksempler:
* [*] ved vedtak

.Eksempel i RDF Turtle
----
@prefix provno: <https://data.norge.no/vocabulary/provno#> .

<A> a dcat:Dataset ;
   prov:wasGeneratedBy provno:administrativeDecision .
----

==== Datasett - datasettdistribusjon [[datasett-datasettdistribusjon]]

.Sammendrag
For å angi hvor man kan få tilgang til datasettet skal det angis ulike distribusjoner [https://data.norge.no/specification/dcat-ap-no/#Datasett-datasettdistribusjon[Datasett: datasettdistribusjon]].

.Anbefalinger
For å angi hvor man kan få tilgang til datasettet skal det angis ulike distribusjoner.

 * Det angis i utgangspunktet en distribusjon per fil, feed eller API
 * Dersom det er ett API som leverer flere filformater angis det som en distribusjon

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
    dcat:distribution <enDistribusjon> . # refererer til en beskrivelse av en distribusjon
----

==== Datasett - dekningsområde [[datasett-dekningsområde]]

.Sammendrag
Angi geografisk avgrensning [https://data.norge.no/specification/dcat-ap-no/#Datasett-dekningsomr%C3%A5de[Datasett: dekningsområde]] dersom datasett kun har innhold fra visse områder. Refererer til geografiske områder angitt med URI fra kontrollerte vokabularer.

.Anbefalinger
Det er ønskelig å synliggjøre om datasettets utvalg er begrenset til bestemte geografiske områder.

 * Angi geografisk avgrensning dersom datasett kun har innhold fra visse områder. “Observert hekking av grågås i Oppdal” er datasettets geografiske omfang begrenset til kommunen Oppdal.
 * Minst en av verdiene skal være fra kontrollerte vokabularer https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/continent[Continent], https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/country[Country], https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/place[Place] eller http://sws.geonames.org/[GenNames].
 * https://data.geonorge.no/administrativeEnheter/nasjon/doc/173163[Administrative enheter] fra Kartverket bør brukes for å angi geografiske områder i Norge.
  * Flere områder kan angis om relevant.

.Eksempler

* [*] [.underline]#Norge# (lenke: http://publications.europa.eu/resource/authority/country/NOR)
* [*] [.underline]#Oppdal# (lenke: https://data.geonorge.no/administrativeEnheter/kommune/id/172879)

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
   dct:spatial <http://publications.europa.eu/resource/authority/country/NOR> , # Norge
      <https://data.geonorge.no/administrativeEnheter/kommune/id/172879> ; # Oppdal
       .
----

==== Datasett - emneord [[datasett-emneord]]

.Sammendrag
Angi sentralt innhold i datasettet som ikke ennå har begrepsdefinisjoner som emneord [https://informasjonsforvaltning.github.io/dcat-ap-no/#Datasett-emneord[Datasett: emneord]].

.Anbefalinger
Ord og uttrykk som hjelper brukeren til å finne datasettet inkluderes (der det ikke er eksplisitt angitt referanser til begreper)

 * Angi synonymer til hjelp i søk
 * Angi sentralt innhold i datasettet som ikke finnes begrepsdefinisjoner for ennå

I noen tilfeller mangler noen av begrepsdefinisjonene som er sentrale for å beskrive datasettet, eller man har et ord som ikke formelt forbindes med datasettet men som man vet at mange likevel bruker. Da kan vi bruke dette feltet for å sørge for at disse emneordene likevel gir treff i søkemotoren.

.Eksempler

* [*] uførepensjon, uførepensjonister, uførereform

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dcat:keyword “uførepensjon”@nb, “uførepensjonister”@nb, “uførereformen”@nb .
----

==== Datasett - følger [[datasett-følger]]

.Sammendrag
Angi referanse til regelverk (inkl. lovhjemmel) som datasettet følger [https://data.norge.no/specification/dcat-ap-no/#Datasett-f%C3%B8lger[Datasett: følger]].

.Anbefalinger
* Angi referanse til regelverk som datasettet følger, og derfra ev. referanse til lovhjemmel.
* For deg som skal utvikle/tilpasse verktøystøtte: det er predefinerte instanser av `cpsv:Rule` for hhv. skjermingsregel (`cpsvno:ruleForNonDisclosure`), utleveringsregel (`cpsvno:ruleForDisclosure`) og behandlingsgrunnlag (`cpsvno:ruleForDataProcessing`), som bør brukes ved angivelse av de aktuelle typer regelverk.

.Eksempler
* [*] Regel for skjerming, med lenke til lovhjemmel.
* [*] Regel for utlevering, med lenke til lovhjemmel.
* [*] Behandlingsgrunnlag, med lenke til lovhjemmel.

.Eksempel i RDF Turtle
----
@prefix cpsvno: <https://data.norge.no/vocabulary/cpsvno#> .

<etDatasett> a dcat:Dataset ;
  cpsv:follows [ a cpsv:Rule ;
        dct:type cpsvno:ruleForNonDisclosure ; # skjermingsregel
        cpsv:implements [ a eli:eli:LegalResource ;
              dct:type <lov> ;
              rdfs:seeAlso "https://lovdata.no/NL/lov/2016-05-27-14/§3-1" ;
              dct:title "Skatteforvaltningsloven §3-1"@nb ;
        ] ;
      ] , [ a cpsv:Rule ;
          dct:type cpsvno:ruleForDisclosure ; # utleveringsregel
          cpsv:implements [ a eli:LegalResource ;
                dct:type <lov> ;
                rdfs:seeAlso "https://lovdata.no/NL/lov/2016-05-27-14/§3-3" ;
                dct:title "Skatteforvaltningsloven §§ 3-3 til 3-9"@nb ;
          ] ;
        ] , [ a cpsv:Rule ;
            dct:type cpsvno:ruleForDataProcessing ; # behandlingsgrunnlag
            cpsv:implements [ a eli:LegalResource ;
                dct:type <lov> ;
                rdfs:seeAlso "https://lovdata.no/NL/lov/2016-05-27-14/§3-3" ;
                dct:title "Skatteforvaltningsloven §§ 3-3 til 3-9"@nb ;
            ] ;
          ] ;
    .

<lov> a skos:Concept ;
  skos:prefLabel "lov"@nb ;
  skos:definition "rettsregler som fastsetter rettigheter og plikter"@nb ;
  .
----

NOTE: Til deg som skal utvikle/tilpasse verktøystøtte: I referanser til Lovdata i RDF-eksemplet ovenfor, er ikke https://lovdata.no/eli/[ELI-standarden] brukt. Dette fordi det p.t. ikke er knyttet funksjonalitet til URI for henvisninger til deler av en lov, f.eks. §3-3. Det vil si at det for øyeblikket er mulig å henvise til deler, men oppslaget vil lede til en hel lov. Se eksempel: https://lovdata.no/eli/lov/2016/05/27/14/nor/section/3-3.

==== Datasett - kontaktpunkt [[datasett-kontaktpunkt]]

.Sammendrag
Angi kontaktinformasjonen [https://data.norge.no/specification/dcat-ap-no/#Datasett-kontaktpunkt[Datasett: kontaktpunkt]] som kan brukes ved henvendelser om et datasett.

.Anbefalinger
Egenskapen kontaktpunkt angis for å komme i dialog med utgiveren av datasettet.

 * Angi kontaktinformasjonen som kan brukes ved henvendelser om et datasett.
 * Vcard https://www.w3.org/TR/vcard-rdf[https://www.w3.org/TR/vcard-rdf] benyttes for å beskrive kontaktpunktet (se anbefaling under hvert Kontaktpunkt-felt)
* Vi anbefaler sterkt å bruke organisatoriske enheter og ikke enkeltpersoner som kontaktpunkt.

.Eksempler

* [*] Opplysningsavdelingen, Brønnøysundregistrene

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
   dcat:contactPoint [ a vcard:Organization ;
      vcard:hasEmail <mailto:OA-fagstillinger@brreg.no> ;
      vcard:organization-unit  "Opplysningsavdelingen, Brønnøysundregistrene" ;
      ] .
----

==== Datasett - tidsrom [[datasett-tidsrom]]

.Sammendrag
Angi tidsmessig avgrensning [https://data.norge.no/specification/dcat-ap-no/#Datasett-tidsrom[Datasett: tidsrom]] dersom datasett kun har innhold fra visse perioder.

.Anbefalinger
En tidsromsangivelse er nødvendig for datasett hvor innholdet dekker et avgrenset tidsrom.

 * Angi tidsmessig  avgrensning dersom datasett kun har innhold fra visse perioder. For mange datasett knyttet til registerfunksjoner vil tidsrom være direkte koblet mot oppdateringsfrekvens. For andre datasett vil tidsrom være vesentlig i forhold til forståelse av bruk av dataene, f.eks. folketellinger.
 * Dersom det er angitt en periode med årstall, tolkes dette som fra og med 1. januar første år til og med 31. desember siste år.
 * Ved ett årstall på begynnelse, men ikke angitt slutt, tolkes det at datasettet har data også i en ubestemt fremtid og tilsvarende om startdatoen mangler antas det at det er ikke angitt om datasettet har en start.
 * Dersom datasettet er en av flere i en tidsserie anbefales det at det lages et overordnet datasett for tidsserien uten distribusjoner som peker på hver datasett.
 * Det benyttes tidsstempel for registreringen av første og siste dataelement i datasettet.
 * Det kan angis flere tidsperioder per datasett, men det anbefales at periodene ikke er overlappende.


.Eksempler

* [*] “1901”

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dct:temporal  [ a dct:PeriodOfTime ;
    ot:hasBeginning  [ a ot:Instant ;
      ot:inXSDDateTime "1901-01-01T00:00:00Z"^^xsd:dateTime ;
      ] ;
    owl:hasEnd [ a ot:Instant ;
      ot:inXSDDateTime "1901-12-31T23:59:59Z"^^xsd:dateTime ;
      ] ;
   ] .
----

==== Datasett - tilgangsnivå [[datasett-tilgangsnivå]]

.Sammendrag
Angi om datasettet er offentlig åpne data, eller er helt eller delvis skjermet for innsyn [https://data.norge.no/specification/dcat-ap-no/#Datasett-tilgangsniv%C3%A5[Datasett: tilgangsnivå]].

.Anbefalinger
Det er behov for å angi i hvilken grad datasettet kan bli gjort tilgjengelig for allmennheten, uten hensyn til om det er publisert eller ikke.

 * Angi om datasettet er helt eller delvis skjermet for innsyn, ved å bruke en av verdiene fra EU sitt kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/access-right[Access right]: "offentlig" (`PUBLIC`), "begrenset offentlighet" (`RESTRICTED`) eller "unntatt offentlighet" (`NON-PUBLIC`).
 ** “Offentlig” brukes når datasettet ikke inneholder begrensede opplysninger og kan legges ut som åpne data, selv om det ikke er laget en løsning for tilgang. Se https://data.norge.no/guide/veileder-apne-data/[Veileder for tilgjengeliggjøring av åpne data].
** “Begrenset offentlighet” brukes når tilgangen til opplysningene avhenger av hvilket formål opplysningene er innsamlet til, og hvilken lovhjemmel den som skal bruke dataene har. Begrensningen kan skyldes innhold som personopplysninger. Når noen ønsker å benytte datasettet må man foreta en konkret vurdering av tilgangen.
** “Unntatt offentlighet” brukes når saksbehandler har med referanse til lov eller forskrift valgt at  datasett (dokumenter eller saksopplysninger) kan unndras fra offentlighet. Typiske eksempler er interne dokumenter, styringsdialog, ansettelser, gradert informasjon, forretningshemmeligheter eller data som andre eier.


 * Skal gjenspeile det mest begrensede feltet/opplysningen i datasettet.

 * Varianter av datasettet kan være offentlig ved at det utelater de felt som gjør at det opprinnelige datasettet er begrenset teller unntatt offentlighet. (se relasjoner mellom datasett).
 * Ved bruk av verdiene "begrenset offentlighet" og "unntatt offentlighet" er egenskapen <<datasett-følger, Datasett - følger>> anbefalt.

.Eksempler
Enhetsregisteret (hele):

* [*] begrenset offentlighet

Enhetsregisteret - Juridisk person (hovedenhet):

* [*] offentlig

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dcat:accessRights <http://publications.europa.eu/resource/authority/access-right/PUBLIC> .
----

=== Valgfrie felter i en datasettbeskrivelse [[datasett-valgfrie-felter]]

I tillegg til obligatoriske (skal brukes) og anbefalte (bør brukes) felter, er det en del felter som er valgfrie (kan brukes) i en datasettbeskrivelse:

* Datasett - annen identifikator: sekundær identifikator til datasettet.
* Datasett - dokumentasjon: referanse til side eller dokument som beskriver datasettet ytterligere.
* Datasett - eksempeldata: referanse til eksempeldata av datasettet.
* Datasett - endringsdato: dato for siste oppdatering av datasettet.
* Datasett - er del av: datasett som dette datasettet er en del av.
* Datasett - er påkrevd av: datasett som er avhengig av dette datasettet.
* Datasett - er referert av: datasett som refererer til dette datasettet.
* Datasett - er versjon av: datasett som dette datasettet er en versjon av.
* Datasett - erstatter: datasett som dette datasettet erstatter.
* Datasett - erstattes av: datasett som er erstattet av dette datasettet.
* Datasett - frekvens: oppdateringsfrekvens av innholdet i datasettet.
* Datasett - har del: datasett som inngår i dette datasettet.
* Datasett - har kvalitetsnote: tekstlig beskrivelse av kvalitet på datasettet.
* Datasett - har måleresultat: kvantifiserbar beskrivelse av kvalitet på datasettet.
* Datasett - har versjon: datasett som er versjon av dette datasettet.
* Datasett - i samsvar med: standard/spesifikasjon (inkl. informasjonsmodell) som datasettet er i samsvar med.
* Datasett - kilde: datasett som dette datasettet er avledet fra.
* Datasett - krever: datasett som dette datasettet er avhengig av.
* Datasett - kvalifisert kreditering: aktør som har en eller annen form for ansvar for datasettet.
* Datasett - kvalifisert relasjon: beslektet ressurs (f.eks. en publikasjon)
* Datasett - landingsside: nettside som gir tilgang til datasettet, tilleggsinfo om datasettet etc.
* Datasett - opphav: beskrivelse av endring i eierskap og forvaltning av datasettet.
* Datasett - produsent: aktør som har produsert datasettet.
* Datasett - refererer til: en annen ressurs som kan være nyttig for brukere av datasettet å være oppmerksom på.
* Datasett - relatert ressurs: annen beslektet ressurs.
* Datasett - romlig oppløsning: minst romlig oppløsning for datasettet.
* Datasett - språk: språk datasettet er på.
* Datasett - tidsoppløsning: miste oppløsning i tidsperiode i datasettet.
* Datasett - type: datasettets type.
* Datasett - utgivelsesdato: dato for den formelle utgivelsen av datasettet.
* Datasett - versjon: versjonsnummer eller annen versjonsbetegnelse for datasettet.
* Datasett - versjonsnote: beskrivelse av forskjellene mellom denne og en tidligere versjon av datasettet.

Ikke alle valgfrie felter er beskrevet i etterfølgende avsnitt. Se under <<hensikt-og-avgrensing, Hensikt og avgrensning>> for hvordan du kan melde inn behov for beskrivelser.

==== Datasett - annen identifikator [[datasett-annenIdentifikator]]

_<ikke beskrevet, tilsvarer [https://data.norge.no/specification/dcat-ap-no/#Datasett-annenIdentifikator[Datasett: annen identifikator]]>_

==== Datasett - dokumentasjon [[datasett-dokumentasjon]]

.Sammendrag
Referanse til en side som inneholder utdypende dokumentasjon om datasettet [https://data.norge.no/specification/dcat-ap-no/#Datasett-dokumentasjon[Datasett: dokumentasjon]].

.Anbefalinger
Utdypende dokumentasjon av datasettet angis ved å peke på en side der den finnes.

.Eksempler

* [*] https://confluence.brreg.no/display/DBNPUB/Informasjonsmodell+for+Enhetsregisteret+og+Foretaksregisteret
----
<etDatasett> a dcat:Dataset ;
  foaf:page <https://confluence.brreg.no/display/DBNPUB/Informasjonsmodell+for+Enhetsregisteret+og+Foretaksregisteret> .
----

==== Datasett - eksempeldata [[datasett-eksempeldata]]


.Sammendrag
Benyttes for å gi eksempeldata for et datasett [https://data.norge.no/specification/dcat-ap-no/#Datasett-eksempeldata[Datasett: eksempeldata]], og hvordan en faktisk distribusjon ser ut.

.Anbefalinger
Benyttes for å gi eksempeldata for et datasett, og hvordan en faktisk distribusjon ser ut.

 * Dersom datasettet inneholder personopplysninger vil det være nyttig for bruker å se et eksempedatasett som f.eks. viser en anonymisert rad i datasettet.

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  adms:sample <distribusjonAvEksempeldata> .

<distribusjonAvEksempeldata> a dcat:Distribution ;
  dcat:accessURL <https://eks.direks.eks/datasets/eksempelData1.csv> .
----

==== Datasett - endringsdato [[datasett-endringsdato]]

.Sammendrag
Tidspunktet angir når innholdet i datasettet sist er endret [https://data.norge.no/specification/dcat-ap-no/#Datasett-endringsdato[Datasett: endringsdato]].

.Anbefalinger
For å forstå når datasettet sist ble oppdatert angis tidspunkt for siste endring

 * Tidspunktet angir når innholdet i datasettet sist er endret.
 * Angis som tidspunkt (dato alene tolkes som kl. 00:00:00 norsk tid).
 * Tidspunkt angis med xsd:data eller xsd:dateTime.

.Eksempler

* [*] 01.01.2017

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dct:modified "2017-01-01"^^xsd:date .
----

==== Datasett - er del av [[datasett-erDelAv]]

.Sammendrag
Der et datasett (f.eks. et register) oppdeles i mindre datasett skal relasjonen [https://data.norge.no/specification/dcat-ap-no/#Datasett-erDelAv[Datasett: er del av]] brukes.

.Anbefalinger
Peker til et datasett som det aktuelle datasettet er en delmengde av, eller at det er brutt opp i mindre datasett.

 * Der registre oppdeles i mindre datasett skal relasjonen brukes. F.eks. er datasettet Underenheter er del av datasettet Enhetsregisteret.

.Eksempel i RDF Turtle
----
<underenheter> a dcat:Dataset ;
  dct:isPartOf <enhetsregisteret> .

<enhetsregisteret> a dcat:Dataset .
----

==== Datasett - er påkrevd av [[datasett-erPåkrevdAv]]

.Sammendrag
Peker til et annet datasett som dette datasettet er nødvendig for [https://data.norge.no/specification/dcat-ap-no/#Datasett-erP%C3%A5krevdAv[Datasett: er påkrevd av]].

.Anbefalinger
Peker til et annet datasett som dette datasettet er nødvendig for.

.Eksempel i RDF Turtle
----
<datasettA> a dcat:Dataset ;
  dct:isRequiredBy <datasettB> .
----

==== Datasett - er referert av [[Datasett-erReferertAv]]

Motsatt av <<datasett-referererTil, Datasett - refererer til>>.

==== Datasett - er versjon av [[datasett-erVersjonAv]]

.Sammendrag
Referanse til et datasett som i prinsippet er det samme, men hvor innholdet er blitt oppdatert, f.eks. på bakgrunn av bedret datakvalitet e.l.

.Anbefalinger

Peker til et datasett som det aktuelle datasettet er en versjon av.

 * I prinsippet det samme datasettet, men hvor innholdet er blitt oppdatert f.eks. på bakgrunn av bedret datakvalitet e.l.

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dct:isVersionOf <forrigeVersjon> .

<forrigeVersjon> a dcat:Dataset .
----

==== Datasett - erstatter [[datasett-erstatter]]

Motsatt av <<datasett-erstattesAv, Datasett - erstattes av>>.

==== Datasett - erstattes av [[datasett-erstattesAv]]

.Sammendrag
Peker til et datasett som erstatter dette datasettet [https://data.norge.no/specification/dcat-ap-no/#Datasett-erstattesAv[Datasett: erstattes av]].

.Anbefalinger
Peker til et datasett som erstatter dette datasettet.

 * F.eks. kan et kodeverk bli erstattet av en nyere utgave.

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dct:isReplacedBy <nyUtgave> .

<nyUtgave> a dcat:Dataset .
----

==== Datasett - frekvens [[datasett-frekvens]]

.Sammendrag
Beskriv hvor ofte datasettet har nytt innhold [https://data.norge.no/specification/dcat-ap-no/#Datasett-frekvens[Datasett: frekvens]].

.Anbefalinger
En angivelse hvor ofte datasettet blir oppdatert.

 * Beskriv hvor ofte datasettet har nytt innhold. For eksempel oppdateres Enhetsregisteret med nye enheter og sletting av enheter _kontinuerlig_, mens Inntektsdata fra likningen (Skattemelding) er _årlig_ og Folketelling fra 1910 oppdateres _aldri_.
 * Begreper (og tilhørende URIer) fra EU sitt kontrollerte vokabular for https://op.europa.eu/s/o16S[Frequency] skal benyttes.

.Eksempler

[*] Daglig

----
<etDatasett> a dcat:Dataset ;
  dct:accruralPeriodicity <http://publications.europa.eu/resource/authority/frequency/DAILY> .
----

==== Datasett - har del [[datasett-harDel]]

Motsatt av <<datasett-erDelAv, Datasett - er del av>>.

==== Datasett - har kvalitetsnote [[datasett-harKvalitetsNote]]

Se under <<beskrivelse-av-kvalitet, Beskrivelse av kvalitet>>.

==== Datasett - har måleresultat [[datasett-harMåleresultat]]

Se under <<beskrivelse-av-kvalitet, Beskrivelse av kvalitet>>.

==== Datasett - har versjon [[datasett-harVersjon]]

_<ikke beskrevet, tilsvarer  [https://data.norge.no/specification/dcat-ap-no/#Datasett-harVersjon[Datasett: har versjon]]>_

==== Datasett - i samsvar [[datasett-iSamsvarMed]]

.Sammendrag
Angi at et datasett er i samsvar med [https://data.norge.no/specification/dcat-ap-no/#Datasett-iSamsvarMed[Datasett: i samsvar med]] en standard, spesifikasjon, en informasjonsmodell, en  implementasjonsregel, eller lignende.

.Anbefalinger
Det er behov for å vite om et datasett er i henhold til gitt(e) standard(er)/spesifikasjon(er)/o.l.

 * Benyttes til å angi at et datasett er i samsvar med en standard, spesifikasjon, informasjonsmodell, implementasjonsregel e.l. Eksempel: Et datasett er i samsvar med SOSI 4.5 som  innholdsstandard.


.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dcat:conformsTo [ a dct:Standard ;
  skos:prefLabel “Produktspesifikasjon NVE flomsoner 1.0”@nb ;
  rdfs:seeAlso <http://sosi.geonorge.no/Produktspesifikasjoner/Produktspesifikasjon_NVE_Flomsoner_1%200.pdf> ;
  ] .
----

==== Datasett - kilde [[datasett-kilde]]

.Sammendrag
Peker til et datasett som helt eller delvis er en kilde for det aktuelle datasettet [https://data.norge.no/specification/dcat-ap-no/#Datasett-kilde[Datasett: kilde]].

.Anbefalinger
Peker til et datasett som er kilde til datasettet.

 * Peker til datasettet som helt eller delvis er en kilde for det aktuelle datasettet.
 * Dersom et åpent datasett er basert på et annet hvor personopplysninger er fjernet, kan relasjonen brukes.
 * Et datasett som er avledet fra et annet skal ha en referanse til kilde for det aktuelle datasettet.
 * Dersom det er et utvalg fra et annet datasett bør heller <<datasett-erDelAV, Datasett - er del av>> brukes.

.Eksempler

----
<etDatasett> dcat:Dataset ;
  dcat:source <kildeDatasett> .

<kildeDatasett> a dcat:Dataset .
----

==== Datasett - krever [[datasett-krever]]

Motsatt av <<datasett-erPåkrevdAv, Datasett: er påkrevd av>>.

==== Datasett - kvalifisert kreditering [[datasett-kvalifisertKreditering]]

_<ikke beskrevet, tilsvarer [https://data.norge.no/specification/dcat-ap-no/#Datasett-kvalifisertKreditering[Datasett: kvalifisert kreditering]]>_


==== Datasett - kvalifisert relasjon [[datasett-kvalifisertRelasjon]]

_<ikke beskrevet, tilsvarer [https://data.norge.no/specification/dcat-ap-no/#Datasett-kvalifisertRelasjon[Datasett: kvalifisert relasjon]]>_

==== Datasett - landingsside [[datasett-landingsside]]

.Sammendrag
Referanse til en side som beskriver datasettet [https://data.norge.no/specification/dcat-ap-no/#Datasett-landingsside[Datasett: landingsside]].

.Anbefalinger

Dokumentasjon om datasettet på en landingsside som kan beskrive datasettets innhold og struktur, og tilgang. Det anbefales at landingsside brukes der man refererer til utfyllende dokumentasjon, og <<datasett-datasettdistribusjon, Datasett - datasettdistribusjon>> benyttes f.eks. når man vil referere til en søkeside.

 * kan referere til datasettets hjemmeside
 * kan referere til en samleside som beskriver innhold og struktur
 * kan referere til en samleside om nedlasting/bruk/søk (tjenestene)
 * det kan refereres til flere sider

.Eksempler

* [*] https://confluence.brreg.no/display/DBNPUB/Informasjonsmodell+for+Enhetsregisteret+og+Foretaksregisteret

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dcat:landingpage
    <https://confluence.brreg.no/display/DBNPUB/Informasjonsmodell+for+Enhetsregisteret+og+Foretaksregisteret>,
    <https://www.brreg.no/om-oss/samfunnsoppdraget-vart/registera-vare/einingsregisteret/> .
----

==== Datasett - opphav [[datasett-opphav]]

_<ikke beskrevet, tilsvarer [https://data.norge.no/specification/dcat-ap-no/#Datasett-opphav[Datasett: opphav]]>_

==== Datasett - produsent [[datasett-produsent]]

.Sammendrag
Brukes unntaksvis der det er datasettet som er satt sammen av data som andre har produsert [https://data.norge.no/specification/dcat-ap-no/#Datasett-produsent[Datasett: produsent]].

.Anbefalinger
Egenskapen angir produsent(er) av datasettet der dette er en annen enn utgiver (<<datasett-utgiver, Datasett - utgiver>>).

 * Brukes unntaksvis der datasettet er satt sammen av data som andre har produsert.
 * Der produsent er en sammensatt gruppe, vil det ikke være mulig å bruke organisasjonsnummer. I så fall kan produsent oppgis som en instans av `foaf:Agent`.

.Eksempler

* [*] “Samarbeidskommunene A, B og C”

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dct:creator <samarbeidsKommunene> .

<samarbeidsKommunene> a foaf:Agent ;
  foaf:name "Samarbeidskommunene A, B og C" .
----

==== Datasett - refererer til [[datasett-referererTil]]

.Sammendrag
Referanse til andre ressurser som det kan være nyttig for brukere å være oppmerksom på [https://data.norge.no/specification/dcat-ap-no/#Datasett-referererTil[Datasett: refererer til]].

.Anbefalinger
Referanse til andre ressurser som det kan være nyttig for brukere å være oppmerksom på.

 * Peker til ressurser som kan være aktuelt å se i sammenheng med det aktuelle datasettet, f.eks. for Enhetsregisteret supplerende informasjon om Enheter, men ikke direkte relatert.

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dct:references [ a dcat:Resource ;
    dct:title “Register over offentlig støtte”@nb ;
    rdfs:seeAlso <http://brreg.no/catalogs/974760673/datasets/ca04abdd-6327-4833-bd05-7a3dca20e6a5> ] .
----

==== Datasett - relatert ressurs [[datasett-relatertRessurs]]

.Sammendrag
Referanse til andre ressurser som gir supplerende informasjon om innholdet i datasettet.

.Anbefalinger
En generell relasjon som peker til ressurser som er relatert til datasettet.

 * Angi referanser til andre ressurser (f.eks. andre datasett) som gir supplerende informasjon om innholdet i dette datasettet. Kan f.eks. være å relatere til et annet register.

.Eksempel i RDF Turtle
----
<etDatasett> dcat:Dataset ;
  dct:relation <relatertDatasett> .

<relatertDatasett> a dcat:Dataset .
----

==== Datasett - romlig oppløsning [[datasett-romligOppløsning]]

_<ikke beskrevet, tilsvarer [https://data.norge.no/specification/dcat-ap-no/#Datasett-romligOppl%C3%B8sning[Datasett: romlig oppløsning]]>_


==== Datasett - språk [[datasett-språk]]

.Sammendrag
Hovedspråket [https://data.norge.no/specification/dcat-ap-no/#Datasett-spr%C3%A5k[Datasett: språk]] benyttet i datasettets innhold angis.

.Anbefalinger
For å forstå hvilket språk innholdet til datasettet har angis dette.

 * Det er hovedspråket benyttet i datasettets innhold som skal angis.
 * Er datasettet uten språklige tekster angis ikke språk.
 * Inneholder datasett tekster på flere språk, og det ikke er tydelig hva som er hovedspråket, angis ikke språk.
 * Språk angis ved å velge fra EUs kontrollerte liste over https://op.europa.eu/s/o19C[Language].

.Eksempler

* [*] Norsk bokmål

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dct:language <http://publications.europa.eu/resource/authority/language/NOB> .
----

==== Datasett - tidsromsoppløsning [[datasett-tidsromsoppløsning]]

_<ikke beskrevet, tilsvarer [https://data.norge.no/specification/dcat-ap-no/#Datasett-tidsoppl%C3%B8sning[Datasett: tidsoppløsning]]>_

==== Datasett - type [[datasett-type]]

.Sammendrag
Referanse til en klassifisering av type innhold i datasettet [https://data.norge.no/specification/dcat-ap-no/#Datasett-type[Datasett: type]].

.Anbefalinger
Referanse til en klassifisering av type innhold i datasettet.

 * EUs kontrollerte vokabular for https://op.europa.eu/s/o19R[Dataset type] bør brukes.

.Eksempel i RDF Turtle
----
<ds1> a dcat:Dataset ;
  dct:type <http://publications.europa.eu/resource/authority/dataset-type/CODE_LIST> . # kodeliste

<ds2> a dcat:Dataset ;
  dct:type <http://publications.europa.eu/resource/authority/dataset-type/SYNTHETIC_DATA> . # kunstig data

<ds3> a dcat:Dataset ;
  dct:type <http://publications.europa.eu/resource/authority/dataset-type/TEST_DATA> . # testdata
----

==== Datasett - utgivelsesdato [[datasett-utgivelsesdato]]

.Sammendrag
Tidspunktet angir når innholdet i datasettet gjøres tilgjengelig [https://data.norge.no/specification/dcat-ap-no/#Datasett-utgivelsesdato[Datasett: utgivelsesdato]].

.Anbefalinger
For å forstå når datasettet er operativt og tilgjengelig angis tidspunkt for utgivelse.

* Angi når innholdet i datasettet gjøres tilgjengelig. Dette er ikke alltid  samsvarende med når den enkelte distribusjonen er tilgjengelig. Og heller ikke når beskrivelsen om datasettet utgis (katalogpostens utgivelse).
 * Angis som xsd:date eller xsd:dateTime.

.Eksempler

* [*] 01.01.2017

.Eksempel i RDF Turtle
----
<etDatasett> a dcat:Dataset ;
  dct:issued “2017-01-01”^^xsd:date .
----

==== Datasett - versjon [[datasett-versjon]]

_<ikke beskrevet, tilsvarer [https://data.norge.no/specification/dcat-ap-no/#Datasett-versjon[Datasett: versjon]]>_

==== Datasett - versjonsnote [[datasett-versjonnote]]

_<ikke beskrevet, tilsvarer [https://data.norge.no/specification/dcat-ap-no/#Datasett-versjonsnote[Datasett: versjonsnote]]>_
